import { useCallback, useEffect, useState } from 'react'
import { API_URL } from '../lib/api.js'
import { accountStatusLabel, ASSIGNABLE_STAFF_ROLES, buildAccountAssignmentPayload, buildGoogleRecoveryPayload, buildStaffAccountPayload, clearOneTimeSecret, STAFF_ROLES } from '../lib/accountAdmin.js'

const emptyForm={username:'',role:'DISCIPLINE_OFFICE',firstName:'',lastName:'',employeeNumber:'',email:''}

function AdminAccounts({token,students=[]}) {
 const [accounts,setAccounts]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[search,setSearch]=useState('')
 const [form,setForm]=useState(emptyForm),[creating,setCreating]=useState(false),[secret,setSecret]=useState(null),[action,setAction]=useState(null),[reason,setReason]=useState(''),[busy,setBusy]=useState(false)
 const [recoveryStudentId,setRecoveryStudentId]=useState(''),[recoveryReason,setRecoveryReason]=useState(''),[recoveryBusy,setRecoveryBusy]=useState(false),[recoverySuccess,setRecoverySuccess]=useState('')
 const [departments,setDepartments]=useState([]),[assignmentAccountId,setAssignmentAccountId]=useState(''),[assignmentRole,setAssignmentRole]=useState('DISCIPLINE_OFFICE'),[assignmentDepartmentId,setAssignmentDepartmentId]=useState(''),[assignmentReason,setAssignmentReason]=useState('')
 const load=useCallback(async()=>{setLoading(true);setError('');try{const query=search.trim()?`?search=${encodeURIComponent(search.trim())}`:'';const response=await fetch(`${API_URL}/api/admin/accounts${query}`,{headers:{Authorization:`Bearer ${token}`}});const data=await response.json().catch(()=>null);if(!response.ok||data?.success===false)throw new Error(data?.message||'Unable to load staff accounts.');setAccounts(Array.isArray(data.accounts)?data.accounts:[])}catch(e){setError(e.message)}finally{setLoading(false)}},[search,token])
 useEffect(()=>{load()},[load])
 useEffect(()=>{let active=true;fetch(`${API_URL}/api/admin/departments`,{headers:{Authorization:`Bearer ${token}`}}).then(response=>response.json().then(data=>({response,data}))).then(({response,data})=>{if(active&&response.ok)setDepartments((data.departments||[]).filter(department=>department.is_active))}).catch(()=>{});return()=>{active=false}},[token])
 const create=async(event)=>{event.preventDefault();setCreating(true);setError('');try{const payload=buildStaffAccountPayload(form);const response=await fetch(`${API_URL}/api/admin/accounts`,{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify(payload)});const data=await response.json().catch(()=>null);if(!response.ok||data?.success===false)throw new Error(data?.message||'Unable to create account.');setSecret({password:data.temporary_password,username:data.account.username});setForm(emptyForm);await load()}catch(e){setError(e.message)}finally{setCreating(false)}}
 const applyAction=async(event)=>{event.preventDefault();if(!action||!reason.trim())return setError('Enter a reason before continuing.');if(action.type==='assignment'&&assignmentRole==='DEPARTMENT_HEAD'&&!assignmentDepartmentId)return setError('Select an active department for the Department Head.');setBusy(true);setError('');try{const isReset=action.type==='reset',isAssignment=action.type==='assignment';const endpoint=isReset?'password-reset':isAssignment?'assignment':'status';const body=isReset?{reason:reason.trim()}:isAssignment?buildAccountAssignmentPayload({role:assignmentRole,departmentId:assignmentDepartmentId,reason}):{is_active:!action.account.is_active,reason:reason.trim()};const response=await fetch(`${API_URL}/api/admin/accounts/${action.account.id}/${endpoint}`,{method:isReset?'POST':'PATCH',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await response.json().catch(()=>null);if(!response.ok||data?.success===false)throw new Error(data?.message||'Unable to update account.');if(isReset)setSecret({password:data.temporary_password,username:action.account.username});setAction(null);setReason('');await load()}catch(e){setError(e.message)}finally{setBusy(false)}}
 const closeSecret=()=>setSecret(clearOneTimeSecret())
 const recoverGoogleLink=async(event)=>{event.preventDefault();if(!recoveryStudentId||!recoveryReason.trim())return setError('Select a student and enter a recovery reason.');setRecoveryBusy(true);setRecoverySuccess('');setError('');try{const response=await fetch(`${API_URL}/api/admin/students/${recoveryStudentId}/google-link/revoke`,{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify(buildGoogleRecoveryPayload(recoveryReason))});const data=await response.json().catch(()=>null);if(!response.ok||data?.success===false)throw new Error(data?.message||'Unable to recover this Google link.');setRecoveryStudentId('');setRecoveryReason('');setRecoverySuccess('Google access was revoked. Existing sessions are invalid, and the student must use the normal Google linking flow again.')}catch(e){setError(e.message)}finally{setRecoveryBusy(false)}}
 const applyAssignment=async(event)=>{event.preventDefault();if(!assignmentAccountId||!assignmentReason.trim())return setError('Select an account and enter a reassignment reason.');if(assignmentRole==='DEPARTMENT_HEAD'&&!assignmentDepartmentId)return setError('Select an active department for the Department Head.');setBusy(true);setError('');try{const response=await fetch(`${API_URL}/api/admin/accounts/${assignmentAccountId}/assignment`,{method:'PATCH',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify(buildAccountAssignmentPayload({role:assignmentRole,departmentId:assignmentDepartmentId,reason:assignmentReason}))});const data=await response.json().catch(()=>null);if(!response.ok||data?.success===false)throw new Error(data?.message||'Unable to update the role or department.');setAssignmentAccountId('');setAssignmentRole('DISCIPLINE_OFFICE');setAssignmentDepartmentId('');setAssignmentReason('');await load()}catch(e){setError(e.message)}finally{setBusy(false)}}
 return <section className="registration-review-page" aria-labelledby="accounts-title"><div className="department-welcome"><div><p className="eyebrow">System administration</p><h2 id="accounts-title">Staff accounts</h2><p>Create individually attributable staff accounts and manage their credential status.</p></div><span className="status-badge">{accounts.length} shown</span></div>
 {secret&&<section className="table-card registration-pending" role="alert"><h3>Copy this temporary password now</h3><p>It cannot be retrieved again. Deliver it through the school’s approved private channel.</p><dl><div><dt>Username</dt><dd>{secret.username}</dd></div><div><dt>Temporary password</dt><dd><code>{secret.password}</code></dd></div></dl><button type="button" onClick={closeSecret}>I have stored it securely</button></section>}
 {error&&<p className="error-message" role="alert">{error}</p>}
 <section className="table-card form-card"><div className="table-header"><h3>Create staff account</h3><span>Admin only</span></div><form className="student-form" onSubmit={create}><div className="student-form-grid"><label>Username<input value={form.username} onChange={e=>setForm({...form,username:e.target.value})} autoComplete="off" required/></label><label>Role<select value={form.role} onChange={e=>setForm({...form,role:e.target.value})}>{STAFF_ROLES.map(role=><option key={role} value={role}>{role.replaceAll('_',' ')}</option>)}</select></label><label>First name<input value={form.firstName} onChange={e=>setForm({...form,firstName:e.target.value})} autoComplete="given-name" required/></label><label>Last name<input value={form.lastName} onChange={e=>setForm({...form,lastName:e.target.value})} autoComplete="family-name" required/></label><label>Employee number (optional)<input value={form.employeeNumber} onChange={e=>setForm({...form,employeeNumber:e.target.value})}/></label><label>Email (optional)<input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label></div><button disabled={creating}>{creating?'Creating…':'Create individual account'}</button></form></section>
 <section className="table-card"><div className="table-header"><h3>Account directory</h3><form onSubmit={e=>{e.preventDefault();load()}}><input aria-label="Search staff accounts" placeholder="Search username or name" value={search} onChange={e=>setSearch(e.target.value)}/></form></div>{loading?<p className="empty-state" aria-live="polite">Loading staff accounts…</p>:accounts.length===0?<div className="department-empty"><h4>No staff accounts found</h4><p>Create an individual account or change the search.</p></div>:<div className="registration-review-list">{accounts.map(account=><article key={account.id}><div className="registration-review-heading"><div><h4>{account.first_name} {account.last_name}</h4><p>{account.username} · {account.role.replaceAll('_',' ')}</p></div><span className="status-badge">{accountStatusLabel(account)}</span></div><dl><div><dt>Department</dt><dd>{account.department_name||'Not applicable'}</dd></div><div><dt>Password change</dt><dd>{account.must_change_password?'Required':'Complete'}</dd></div></dl><div className="registration-review-actions"><button type="button" onClick={()=>{setAction({type:'status',account});setReason('')}}>{account.is_active?'Deactivate':'Activate'}</button><button type="button" className="secondary-button" onClick={()=>{setAction({type:'reset',account});setReason('')}}>Reset password</button></div></article>)}</div>}</section>
 {action&&<section className="table-card"><h3>{action.type==='reset'?'Reset password':`${action.account.is_active?'Deactivate':'Activate'} account`}</h3><p>This will invalidate the account’s existing sessions.</p><form className="login-form" onSubmit={applyAction}><label>Required reason<textarea value={reason} onChange={e=>setReason(e.target.value)} maxLength="1000" required autoFocus/></label><div className="registration-review-actions"><button disabled={busy}>Confirm action</button><button type="button" className="secondary-button" onClick={()=>{setAction(null);setReason('')}} disabled={busy}>Cancel</button></div></form></section>}
 <section className="table-card form-card"><div className="table-header"><div><h3>Student Google recovery</h3><p>Use only after confirming the student’s identity. This preserves link history and invalidates existing sessions.</p></div><span>Admin only</span></div>{recoverySuccess&&<p className="success-message" role="status">{recoverySuccess}</p>}<form className="student-form" onSubmit={recoverGoogleLink}><div className="student-form-grid"><label>Student<select value={recoveryStudentId} onChange={e=>{setRecoveryStudentId(e.target.value);setRecoverySuccess('')}} required><option value="">Select student</option>{students.map(student=><option key={student.id} value={student.id}>{student.student_number} — {student.first_name} {student.last_name}</option>)}</select></label><label>Required recovery reason<textarea value={recoveryReason} onChange={e=>setRecoveryReason(e.target.value)} maxLength="1000" required/></label></div><button disabled={recoveryBusy||students.length===0}>{recoveryBusy?'Revoking…':'Revoke Google access'}</button>{students.length===0&&<p className="empty-state">No student records are available for recovery.</p>}</form></section>
 <section className="table-card form-card"><div className="table-header"><div><h3>Role and department assignment</h3><p>Changing an assignment invalidates existing sessions and is recorded in the audit log.</p></div><span>Admin only</span></div><form className="student-form" onSubmit={applyAssignment}><div className="student-form-grid"><label>Staff account<select value={assignmentAccountId} onChange={e=>{const account=accounts.find(item=>String(item.id)===e.target.value);setAssignmentAccountId(e.target.value);setAssignmentRole(account?.role||'DISCIPLINE_OFFICE');setAssignmentDepartmentId(account?.department_id?String(account.department_id):'')}} required><option value="">Select account</option>{accounts.map(account=><option key={account.id} value={account.id}>{account.username} — {account.role.replaceAll('_',' ')}</option>)}</select></label><label>Role<select value={assignmentRole} onChange={e=>{setAssignmentRole(e.target.value);if(e.target.value!=='DEPARTMENT_HEAD')setAssignmentDepartmentId('')}}>{ASSIGNABLE_STAFF_ROLES.map(role=><option key={role} value={role}>{role.replaceAll('_',' ')}</option>)}</select></label>{assignmentRole==='DEPARTMENT_HEAD'&&<label>Active department<select value={assignmentDepartmentId} onChange={e=>setAssignmentDepartmentId(e.target.value)} required><option value="">Select department</option>{departments.map(department=><option key={department.id} value={department.id}>{department.department_name}</option>)}</select></label>}<label>Required reason<textarea value={assignmentReason} onChange={e=>setAssignmentReason(e.target.value)} maxLength="1000" required/></label></div><button disabled={busy||accounts.length===0}>{busy?'Saving…':'Save assignment'}</button></form></section>
 </section>
}
export default AdminAccounts
