import { useCallback, useEffect, useState } from 'react'
import { API_URL } from '../lib/api.js'
import { accountStatusLabel, buildStaffAccountPayload, clearOneTimeSecret, STAFF_ROLES } from '../lib/accountAdmin.js'

const emptyForm={username:'',role:'DISCIPLINE_OFFICE',firstName:'',lastName:'',employeeNumber:'',email:''}

function AdminAccounts({token}) {
 const [accounts,setAccounts]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[search,setSearch]=useState('')
 const [form,setForm]=useState(emptyForm),[creating,setCreating]=useState(false),[secret,setSecret]=useState(null),[action,setAction]=useState(null),[reason,setReason]=useState(''),[busy,setBusy]=useState(false)
 const load=useCallback(async()=>{setLoading(true);setError('');try{const query=search.trim()?`?search=${encodeURIComponent(search.trim())}`:'';const response=await fetch(`${API_URL}/api/admin/accounts${query}`,{headers:{Authorization:`Bearer ${token}`}});const data=await response.json().catch(()=>null);if(!response.ok||data?.success===false)throw new Error(data?.message||'Unable to load staff accounts.');setAccounts(Array.isArray(data.accounts)?data.accounts:[])}catch(e){setError(e.message)}finally{setLoading(false)}},[search,token])
 useEffect(()=>{load()},[load])
 const create=async(event)=>{event.preventDefault();setCreating(true);setError('');try{const payload=buildStaffAccountPayload(form);const response=await fetch(`${API_URL}/api/admin/accounts`,{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify(payload)});const data=await response.json().catch(()=>null);if(!response.ok||data?.success===false)throw new Error(data?.message||'Unable to create account.');setSecret({password:data.temporary_password,username:data.account.username});setForm(emptyForm);await load()}catch(e){setError(e.message)}finally{setCreating(false)}}
 const applyAction=async(event)=>{event.preventDefault();if(!action||!reason.trim())return setError('Enter a reason before continuing.');setBusy(true);setError('');try{const isReset=action.type==='reset';const response=await fetch(`${API_URL}/api/admin/accounts/${action.account.id}/${isReset?'password-reset':'status'}`,{method:isReset?'POST':'PATCH',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify(isReset?{reason:reason.trim()}:{is_active:!action.account.is_active,reason:reason.trim()})});const data=await response.json().catch(()=>null);if(!response.ok||data?.success===false)throw new Error(data?.message||'Unable to update account.');if(isReset)setSecret({password:data.temporary_password,username:action.account.username});setAction(null);setReason('');await load()}catch(e){setError(e.message)}finally{setBusy(false)}}
 const closeSecret=()=>setSecret(clearOneTimeSecret())
 return <section className="registration-review-page" aria-labelledby="accounts-title"><div className="department-welcome"><div><p className="eyebrow">System administration</p><h2 id="accounts-title">Staff accounts</h2><p>Create individually attributable staff accounts and manage their credential status.</p></div><span className="status-badge">{accounts.length} shown</span></div>
 {secret&&<section className="table-card registration-pending" role="alert"><h3>Copy this temporary password now</h3><p>It cannot be retrieved again. Deliver it through the school’s approved private channel.</p><dl><div><dt>Username</dt><dd>{secret.username}</dd></div><div><dt>Temporary password</dt><dd><code>{secret.password}</code></dd></div></dl><button type="button" onClick={closeSecret}>I have stored it securely</button></section>}
 {error&&<p className="error-message" role="alert">{error}</p>}
 <section className="table-card form-card"><div className="table-header"><h3>Create staff account</h3><span>Admin only</span></div><form className="student-form" onSubmit={create}><div className="student-form-grid"><label>Username<input value={form.username} onChange={e=>setForm({...form,username:e.target.value})} autoComplete="off" required/></label><label>Role<select value={form.role} onChange={e=>setForm({...form,role:e.target.value})}>{STAFF_ROLES.map(role=><option key={role} value={role}>{role.replaceAll('_',' ')}</option>)}</select></label><label>First name<input value={form.firstName} onChange={e=>setForm({...form,firstName:e.target.value})} autoComplete="given-name" required/></label><label>Last name<input value={form.lastName} onChange={e=>setForm({...form,lastName:e.target.value})} autoComplete="family-name" required/></label><label>Employee number (optional)<input value={form.employeeNumber} onChange={e=>setForm({...form,employeeNumber:e.target.value})}/></label><label>Email (optional)<input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label></div><button disabled={creating}>{creating?'Creating…':'Create individual account'}</button></form></section>
 <section className="table-card"><div className="table-header"><h3>Account directory</h3><form onSubmit={e=>{e.preventDefault();load()}}><input aria-label="Search staff accounts" placeholder="Search username or name" value={search} onChange={e=>setSearch(e.target.value)}/></form></div>{loading?<p className="empty-state" aria-live="polite">Loading staff accounts…</p>:accounts.length===0?<div className="department-empty"><h4>No staff accounts found</h4><p>Create an individual account or change the search.</p></div>:<div className="registration-review-list">{accounts.map(account=><article key={account.id}><div className="registration-review-heading"><div><h4>{account.first_name} {account.last_name}</h4><p>{account.username} · {account.role.replaceAll('_',' ')}</p></div><span className="status-badge">{accountStatusLabel(account)}</span></div><dl><div><dt>Department</dt><dd>{account.department_name||'Not applicable'}</dd></div><div><dt>Password change</dt><dd>{account.must_change_password?'Required':'Complete'}</dd></div></dl><div className="registration-review-actions"><button type="button" onClick={()=>{setAction({type:'status',account});setReason('')}}>{account.is_active?'Deactivate':'Activate'}</button><button type="button" className="secondary-button" onClick={()=>{setAction({type:'reset',account});setReason('')}}>Reset password</button></div></article>)}</div>}</section>
 {action&&<section className="table-card"><h3>{action.type==='reset'?'Reset password':`${action.account.is_active?'Deactivate':'Activate'} account`}</h3><p>This will invalidate the account’s existing sessions.</p><form className="login-form" onSubmit={applyAction}><label>Required reason<textarea value={reason} onChange={e=>setReason(e.target.value)} maxLength="1000" required autoFocus/></label><div className="registration-review-actions"><button disabled={busy}>Confirm action</button><button type="button" className="secondary-button" onClick={()=>{setAction(null);setReason('')}} disabled={busy}>Cancel</button></div></form></section>}
 </section>
}
export default AdminAccounts
