import { useCallback, useEffect, useState } from 'react'
import { API_URL, changePassword } from '../lib/api.js'
import { passwordIsStrong } from '../lib/passwordPolicy.js'
import PasswordField from './PasswordField.jsx'
import PasswordRequirements from './PasswordRequirements.jsx'
const headers=(token)=>({Authorization:`Bearer ${token}`,'Content-Type':'application/json'})
export default function AdminAccountSettings({token,onSession}){
 const [profile,setProfile]=useState({first_name:'',last_name:'',username:'',email:'',email_verified:false}),[password,setPassword]=useState({current:'',next:'',confirm:''}),[code,setCode]=useState('')
 const [loading,setLoading]=useState(true),[busy,setBusy]=useState(''),[error,setError]=useState(''),[success,setSuccess]=useState('')
 const load=useCallback(async()=>{setLoading(true);try{const response=await fetch(`${API_URL}/api/account/admin-profile`,{headers:headers(token)});const data=await response.json();if(!response.ok)throw new Error(data.message);setProfile(data.profile)}catch(e){setError(e.message)}finally{setLoading(false)}},[token]);useEffect(()=>{load()},[load])
 const save=async(e)=>{e.preventDefault();setBusy('profile');setError('');setSuccess('');try{const response=await fetch(`${API_URL}/api/account/admin-profile`,{method:'PATCH',headers:headers(token),body:JSON.stringify({first_name:profile.first_name,last_name:profile.last_name,username:profile.username,email:profile.email})});const data=await response.json();if(!response.ok)throw new Error(data.message);setProfile(data.profile);setSuccess(data.verification_required?'Profile saved. Enter the code sent to your new email.':'Profile saved successfully.')}catch(x){setError(x.message)}finally{setBusy('')}}
 const verify=async(e)=>{e.preventDefault();setBusy('verify');setError('');try{const response=await fetch(`${API_URL}/api/account/admin-profile/email/verify`,{method:'POST',headers:headers(token),body:JSON.stringify({code})});const data=await response.json();if(!response.ok)throw new Error(data.message);setProfile(data.profile);setCode('');setSuccess('Recovery email verified.')}catch(x){setError(x.message)}finally{setBusy('')}}
 const resend=async()=>{setBusy('resend');setError('');try{const response=await fetch(`${API_URL}/api/account/admin-profile/email/resend`,{method:'POST',headers:headers(token),body:'{}'});const data=await response.json();if(!response.ok)throw new Error(data.message);setSuccess('A new verification code was sent.')}catch(x){setError(x.message)}finally{setBusy('')}}
 const change=async(e)=>{e.preventDefault();setError('');setSuccess('');if(!passwordIsStrong(password.next))return setError('Complete all password requirements.');if(password.next!==password.confirm)return setError('New password confirmation does not match.');setBusy('password');try{const session=await changePassword({token,currentPassword:password.current,newPassword:password.next});setPassword({current:'',next:'',confirm:''});setSuccess('Password changed. Other sessions have been invalidated.');onSession(session)}catch(x){setError(x.message)}finally{setBusy('')}}
 return <section className="admin-settings-page" aria-labelledby="admin-settings-title"><div className="department-welcome"><div><p className="eyebrow">Personal security</p><h2 id="admin-settings-title">Account Settings</h2><p>Manage the primary administrator identity, verified recovery email, and password.</p></div><span className="status-badge">ADMIN</span></div>{error&&<p className="error-message" role="alert">{error}</p>}{success&&<p className="success-message" role="status">{success}</p>}
 {loading?<section className="table-card"><p className="empty-state">Loading account settings…</p></section>:<div className="admin-settings-grid"><section className="table-card form-card"><div className="table-header"><div><h3>Administrator profile</h3><p>Your role cannot be changed here.</p></div><span>{profile.email_verified?'Email verified':'Verification required'}</span></div><form className="student-form" onSubmit={save}><div className="student-form-grid"><label>First name<input value={profile.first_name} onChange={e=>setProfile({...profile,first_name:e.target.value})} required/></label><label>Last name<input value={profile.last_name} onChange={e=>setProfile({...profile,last_name:e.target.value})} required/></label><label>Username<input value={profile.username} onChange={e=>setProfile({...profile,username:e.target.value})} required autoCapitalize="none"/></label><label>Registered email<input type="email" value={profile.email} onChange={e=>setProfile({...profile,email:e.target.value})} required/></label></div><button disabled={Boolean(busy)}>{busy==='profile'?'Saving…':'Save profile'}</button></form>{profile.email&&!profile.email_verified&&<form className="email-verification-box" onSubmit={verify}><h4>Verify recovery email</h4><p>Enter the six-digit code sent to {profile.email}.</p><label>Verification code<input value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,'').slice(0,6))} inputMode="numeric" pattern="[0-9]{6}" required/></label><div className="registration-review-actions"><button disabled={busy==='verify'||code.length!==6}>{busy==='verify'?'Verifying…':'Verify email'}</button><button type="button" className="secondary-button" onClick={resend} disabled={Boolean(busy)}>{busy==='resend'?'Sending…':'Resend code'}</button></div></form>}</section>
 <section className="table-card form-card"><div className="table-header"><div><h3>Change password</h3><p>Changing it signs out every other active session.</p></div></div><form className="login-form" onSubmit={change}><PasswordField id="admin-current-password" label="Current password" value={password.current} onChange={e=>setPassword({...password,current:e.target.value})} autoComplete="current-password" disabled={Boolean(busy)}/><PasswordField id="admin-new-password" label="New password" value={password.next} onChange={e=>setPassword({...password,next:e.target.value})} disabled={Boolean(busy)}/><PasswordRequirements password={password.next}/><PasswordField id="admin-confirm-password" label="Confirm new password" value={password.confirm} onChange={e=>setPassword({...password,confirm:e.target.value})} disabled={Boolean(busy)}/><button disabled={Boolean(busy)||!passwordIsStrong(password.next)}>{busy==='password'?'Changing password…':'Change password'}</button></form></section></div>}</section>
}
