import {useCallback,useEffect,useState} from 'react'
import {API_URL} from '../lib/api.js'
import {buildDepartmentPayload,departmentCanDeactivate} from '../lib/departmentAdmin.js'
const empty={code:'',name:'',description:''}
function AdminDepartments({token}){const [items,setItems]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[form,setForm]=useState(empty),[creating,setCreating]=useState(false),[editing,setEditing]=useState(null),[reason,setReason]=useState(''),[busy,setBusy]=useState(false)
 const load=useCallback(async()=>{setLoading(true);setError('');try{const response=await fetch(`${API_URL}/api/admin/departments`,{headers:{Authorization:`Bearer ${token}`}});const data=await response.json().catch(()=>null);if(!response.ok||data?.success===false)throw new Error(data?.message||'Unable to load departments.');setItems(data.departments||[])}catch(e){setError(e.message)}finally{setLoading(false)}},[token]);useEffect(()=>{load()},[load])
 const create=async(e)=>{e.preventDefault();setCreating(true);setError('');try{const response=await fetch(`${API_URL}/api/admin/departments`,{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify(buildDepartmentPayload(form))});const data=await response.json().catch(()=>null);if(!response.ok||data?.success===false)throw new Error(data?.message||'Unable to create department.');setForm(empty);await load()}catch(x){setError(x.message)}finally{setCreating(false)}}
 const update=async(e)=>{e.preventDefault();if(!reason.trim())return setError('Enter a reason before updating the department.');setBusy(true);setError('');try{const response=await fetch(`${API_URL}/api/admin/departments/${editing.id}`,{method:'PATCH',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({department_code:editing.department_code,department_name:editing.department_name,description:editing.description||'',is_active:editing.is_active,reason:reason.trim()})});const data=await response.json().catch(()=>null);if(!response.ok||data?.success===false)throw new Error(data?.message||'Unable to update department.');setEditing(null);setReason('');await load()}catch(x){setError(x.message)}finally{setBusy(false)}}
 return <section className="registration-review-page"><div className="department-welcome"><div><p className="eyebrow">System administration</p><h2>Departments</h2><p>Maintain official service locations and protect active officer assignments.</p></div><span className="status-badge">{items.length} configured</span></div>{error&&<p className="error-message" role="alert">{error}</p>}
 <section className="table-card form-card"><div className="table-header"><h3>Create department</h3><span>Official configuration</span></div><form className="student-form" onSubmit={create}><div className="student-form-grid"><label>Department code<input value={form.code} onChange={e=>setForm({...form,code:e.target.value})} maxLength="50" placeholder="LIB" required/></label><label>Official name<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} maxLength="150" placeholder="Library" required/></label><label>Description (optional)<input value={form.description} onChange={e=>setForm({...form,description:e.target.value})} maxLength="1000"/></label></div><button disabled={creating}>{creating?'Creating…':'Create department'}</button></form></section>
 <section className="table-card"><div className="table-header"><h3>Department directory</h3></div>{loading?<p className="empty-state">Loading departments…</p>:items.length===0?<div className="department-empty"><h4>No departments configured</h4></div>:<div className="registration-review-list">{items.map(item=><article key={item.id}><div className="registration-review-heading"><div><h4>{item.department_name}</h4><p>{item.department_code}</p></div><span className="status-badge">{item.is_active?'Active':'Inactive'}</span></div><dl><div><dt>Assigned accounts</dt><dd>{item.assigned_accounts}</dd></div><div><dt>Active accounts</dt><dd>{item.active_accounts}</dd></div><div><dt>Description</dt><dd>{item.description||'None'}</dd></div></dl><button type="button" onClick={()=>{setEditing({...item});setReason('')}}>Edit configuration</button></article>)}</div>}</section>
 {editing&&<section className="table-card"><h3>Edit {editing.department_name}</h3><form className="student-form" onSubmit={update}><div className="student-form-grid"><label>Department code<input value={editing.department_code} onChange={e=>setEditing({...editing,department_code:e.target.value})} required/></label><label>Official name<input value={editing.department_name} onChange={e=>setEditing({...editing,department_name:e.target.value})} required/></label><label>Description<textarea value={editing.description||''} onChange={e=>setEditing({...editing,description:e.target.value})}/></label><label>Status<select value={editing.is_active?'active':'inactive'} onChange={e=>setEditing({...editing,is_active:e.target.value==='active'})} disabled={editing.is_active&& !departmentCanDeactivate(editing)}><option value="active">Active</option><option value="inactive">Inactive</option></select>{editing.is_active&&!departmentCanDeactivate(editing)&&<span>Reassign or deactivate active accounts first.</span>}</label><label>Required reason<textarea value={reason} onChange={e=>setReason(e.target.value)} maxLength="1000" required/></label></div><div className="registration-review-actions"><button disabled={busy}>Save changes</button><button type="button" className="secondary-button" onClick={()=>{setEditing(null);setReason('')}} disabled={busy}>Cancel</button></div></form></section>}
 </section>}
export default AdminDepartments
