import { useCallback, useEffect, useMemo, useState } from 'react'
import { API_URL } from '../lib/api.js'
import Modal from './Modal.jsx'
import { buildDepartmentOfficerPayload, departmentStepValid, filterDepartmentOfficers, OFFICER_ROLES, officerStepValid } from '../lib/departmentOfficerAdmin.js'

const empty = { departmentName:'', departmentType:'', description:'', departmentStatus:'active', firstName:'', lastName:'', username:'', role:'DISCIPLINE_OFFICE', email:'', employeeNumber:'' }
const auth = (token) => ({ Authorization:`Bearer ${token}`, 'Content-Type':'application/json' })
const roleLabel = (role) => role?.replaceAll('_',' ') || 'Officer'

function AdminDepartmentOfficers({ token }) {
  const [tab,setTab]=useState('directory'),[step,setStep]=useState(1),[form,setForm]=useState(empty)
  const [accounts,setAccounts]=useState([]),[departments,setDepartments]=useState([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState('')
  const [secret,setSecret]=useState(null),[selected,setSelected]=useState(null),[editDepartment,setEditDepartment]=useState(null),[editOfficer,setEditOfficer]=useState(null),[action,setAction]=useState(null)
  const [filters,setFilters]=useState({search:'',role:'ALL',status:'ALL'}),[reason,setReason]=useState('')
  const load=useCallback(async()=>{setLoading(true);setError('');try{const headers=auth(token);const [a,d]=await Promise.all([fetch(`${API_URL}/api/admin/accounts?limit=100`,{headers}),fetch(`${API_URL}/api/admin/departments`,{headers})]);const [ad,dd]=await Promise.all([a.json(),d.json()]);if(!a.ok)throw new Error(ad.message||'Unable to load officer accounts.');if(!d.ok)throw new Error(dd.message||'Unable to load departments.');setAccounts((ad.accounts||[]).filter(x=>OFFICER_ROLES.includes(x.role)));setDepartments(dd.departments||[])}catch(e){setError(e.message)}finally{setLoading(false)}},[token])
  useEffect(()=>{load()},[load])
  const visible=useMemo(()=>filterDepartmentOfficers(accounts,departments,filters),[accounts,departments,filters])
  const counts=useMemo(()=>({departments:departments.length,active:accounts.filter(x=>x.is_active).length,heads:accounts.filter(x=>x.role==='DEPARTMENT_HEAD').length,discipline:accounts.filter(x=>x.role==='DISCIPLINE_OFFICE').length}),[accounts,departments])
  const change=(key)=>(event)=>setForm(current=>({...current,[key]:event.target.value}))
  const create=async(event)=>{event.preventDefault();if(!officerStepValid(form))return;setBusy(true);setError('');try{const response=await fetch(`${API_URL}/api/admin/accounts/department-officer`,{method:'POST',headers:auth(token),body:JSON.stringify(buildDepartmentOfficerPayload(form))});const data=await response.json();if(!response.ok)throw new Error(data.message||'Unable to create department and officer.');setSecret({username:data.account.username,password:data.temporary_password});setForm(empty);setStep(1);setTab('directory');await load()}catch(e){setError(e.message)}finally{setBusy(false)}}
  const saveDepartment=async(event)=>{event.preventDefault();if(!reason.trim())return setError('A reason is required.');setBusy(true);try{const response=await fetch(`${API_URL}/api/admin/departments/${editDepartment.id}`,{method:'PATCH',headers:auth(token),body:JSON.stringify({department_code:editDepartment.department_code,department_name:editDepartment.department_name,department_type:editDepartment.department_type,description:editDepartment.description||'',is_active:editDepartment.is_active,reason:reason.trim()})});const data=await response.json();if(!response.ok)throw new Error(data.message);setEditDepartment(null);setReason('');await load()}catch(e){setError(e.message)}finally{setBusy(false)}}
  const saveOfficer=async(event)=>{event.preventDefault();if(!reason.trim())return setError('A reason is required.');setBusy(true);try{const response=await fetch(`${API_URL}/api/admin/accounts/${editOfficer.id}/profile`,{method:'PATCH',headers:auth(token),body:JSON.stringify({username:editOfficer.username,first_name:editOfficer.first_name,last_name:editOfficer.last_name,employee_number:editOfficer.employee_number||'',email:editOfficer.email||'',reason:reason.trim()})});const data=await response.json();if(!response.ok)throw new Error(data.message);setEditOfficer(null);setReason('');await load()}catch(e){setError(e.message)}finally{setBusy(false)}}
  const runAction=async(event)=>{event.preventDefault();if(!reason.trim())return setError('A reason is required.');setBusy(true);try{const reset=action.kind==='reset';const response=await fetch(`${API_URL}/api/admin/accounts/${action.account.id}/${reset?'password-reset':'status'}`,{method:reset?'POST':'PATCH',headers:auth(token),body:JSON.stringify(reset?{reason:reason.trim()}:{is_active:!action.account.is_active,reason:reason.trim()})});const data=await response.json();if(!response.ok)throw new Error(data.message);if(reset)setSecret({username:action.account.username,password:data.temporary_password});setAction(null);setReason('');await load()}catch(e){setError(e.message)}finally{setBusy(false)}}
  return <section className="department-officer-page" aria-labelledby="department-officer-title">
    <div className="department-welcome"><div><p className="eyebrow">System administration</p><h2 id="department-officer-title">Departments &amp; Officer Accounts</h2><p>Create departments with accountable officers and manage access from one secure directory.</p></div><div className="department-officer-tabs" role="tablist"><button className={tab==='directory'?'active':''} onClick={()=>setTab('directory')}>Directory</button><button className={tab==='create'?'active':''} onClick={()=>setTab('create')}>Create department &amp; officer</button></div></div>
    {error&&<p className="error-message" role="alert">{error}</p>}
    {tab==='create'?<section className="table-card department-officer-create"><div className="compact-stepper" aria-label="Creation progress"><button className={step===1?'active':''} onClick={()=>setStep(1)}><b>1</b> Department details</button><span>→</span><button className={step===2?'active':''} disabled={!departmentStepValid(form)} onClick={()=>setStep(2)}><b>2</b> Officer account</button></div>
      {step===1?<form className="student-form" onSubmit={e=>{e.preventDefault();setStep(2)}}><div className="section-heading"><h3>Department details</h3><p>The internal department code is generated safely from its type.</p></div><div className="student-form-grid"><label>Department name<input value={form.departmentName} onChange={change('departmentName')} placeholder="Student Affairs Office" maxLength="150" required/></label><label>Department type<input value={form.departmentType} onChange={change('departmentType')} placeholder="Student Services" maxLength="50" required/></label><label className="full-field">Description (optional)<textarea value={form.description} onChange={change('description')} maxLength="1000"/></label><label>Status<select value={form.departmentStatus} onChange={change('departmentStatus')}><option value="active">Active</option><option value="inactive">Inactive</option></select></label></div><div className="wizard-actions"><span/><button disabled={!departmentStepValid(form)}>Next: Officer account</button></div></form>
      :<form className="student-form" onSubmit={create}><div className="section-heading"><h3>Officer account</h3><p>A one-time password will be generated and must be changed at first sign-in.</p></div><div className="student-form-grid"><label>First name<input value={form.firstName} onChange={change('firstName')} required/></label><label>Last name<input value={form.lastName} onChange={change('lastName')} required/></label><label>Username<input value={form.username} onChange={change('username')} autoCapitalize="none" required/></label><label>Role<select value={form.role} onChange={change('role')}>{OFFICER_ROLES.map(role=><option key={role} value={role}>{roleLabel(role)}</option>)}</select></label><label>Email (optional)<input type="email" value={form.email} onChange={change('email')}/></label><label>Employee number (optional)<input value={form.employeeNumber} onChange={change('employeeNumber')}/></label></div><div className="wizard-actions"><button type="button" className="secondary-button" onClick={()=>setStep(1)}>Back</button><button disabled={busy||!officerStepValid(form)}>{busy?'Creating securely…':'Create department & officer'}</button></div></form>}</section>
    :<><div className="department-summary-grid"><article><b>{counts.departments}</b><span>Total departments</span></article><article><b>{counts.active}</b><span>Active officers</span></article><article><b>{counts.heads}</b><span>Department heads</span></article><article><b>{counts.discipline}</b><span>Discipline officers</span></article></div><section className="table-card"><div className="directory-toolbar"><input aria-label="Search directory" placeholder="Search department, officer, or username" value={filters.search} onChange={e=>setFilters({...filters,search:e.target.value})}/><select aria-label="Filter by role" value={filters.role} onChange={e=>setFilters({...filters,role:e.target.value})}><option value="ALL">All roles</option>{OFFICER_ROLES.map(role=><option key={role} value={role}>{roleLabel(role)}</option>)}</select><select aria-label="Filter by status" value={filters.status} onChange={e=>setFilters({...filters,status:e.target.value})}><option value="ALL">All statuses</option><option value="ACTIVE">Active</option><option value="INACTIVE">Inactive</option></select></div>{loading?<p className="empty-state">Loading directory…</p>:visible.length===0?<div className="department-empty"><h4>No matching officer accounts</h4><p>Adjust the filters or create a department and officer.</p></div>:<div className="officer-directory">{visible.map(account=>{const department=departments.find(d=>Number(d.id)===Number(account.department_id));return <article key={account.id}><div><span className={`status-badge ${account.is_active?'':'status-badge--muted'}`}>{account.is_active?'Active':'Inactive'}</span><h3>{account.department_name||'Unassigned department'}</h3><p className="officer-name">{account.first_name} {account.last_name}</p><p>{account.username} · {roleLabel(account.role)}</p></div><dl><div><dt>Email</dt><dd>{account.email||'Not provided'}</dd></div><div><dt>Employee no.</dt><dd>{account.employee_number||'Not provided'}</dd></div><div><dt>Password</dt><dd>{account.must_change_password?'Change required':'Updated'}</dd></div><div><dt>Created</dt><dd>{new Date(account.created_at).toLocaleDateString()}</dd></div></dl><div className="registration-review-actions"><button onClick={()=>setSelected({...account,department})}>View details</button><button className="secondary-button" onClick={()=>{setEditOfficer({...account});setReason('')}}>Edit officer</button>{department&&<button className="secondary-button" onClick={()=>{setEditDepartment({...department});setReason('')}}>Edit department</button>}<button className="secondary-button" onClick={()=>{setAction({kind:'reset',account});setReason('')}}>Reset password</button><button className="secondary-button danger-button" onClick={()=>{setAction({kind:'status',account});setReason('')}}>{account.is_active?'Deactivate':'Activate'}</button></div></article>})}</div>}</section></>}
    {secret&&<Modal title="One-time temporary password" onClose={()=>setSecret(null)}><div className="one-time-secret" role="alert"><p>Copy this now. It is never stored or shown again.</p><label>Username<code>{secret.username}</code></label><label>Temporary password<code>{secret.password}</code></label><button onClick={()=>navigator.clipboard?.writeText(secret.password)}>Copy password</button><button className="secondary-button" onClick={()=>setSecret(null)}>I stored it securely</button></div></Modal>}
    {selected&&<Modal title="Department & officer details" onClose={()=>setSelected(null)} wide><div className="detail-summary"><h3>{selected.department_name}</h3><p>{selected.department?.description||'No department description.'}</p><dl><div><dt>Officer</dt><dd>{selected.first_name} {selected.last_name}</dd></div><div><dt>Username</dt><dd>{selected.username}</dd></div><div><dt>Role</dt><dd>{roleLabel(selected.role)}</dd></div><div><dt>Account status</dt><dd>{selected.is_active?'Active':'Inactive'}</dd></div><div><dt>Department status</dt><dd>{selected.department?.is_active?'Active':'Inactive'}</dd></div></dl></div></Modal>}
    {editDepartment&&<Modal title="Edit department" onClose={()=>setEditDepartment(null)}><form className="login-form" onSubmit={saveDepartment}><label>Name<input value={editDepartment.department_name} onChange={e=>setEditDepartment({...editDepartment,department_name:e.target.value})} required/></label><label>Type<input value={editDepartment.department_type||''} onChange={e=>setEditDepartment({...editDepartment,department_type:e.target.value.toUpperCase()})} required/></label><label>Description<textarea value={editDepartment.description||''} onChange={e=>setEditDepartment({...editDepartment,description:e.target.value})}/></label><label>Status<select value={editDepartment.is_active?'active':'inactive'} onChange={e=>setEditDepartment({...editDepartment,is_active:e.target.value==='active'})}><option value="active">Active</option><option value="inactive">Inactive</option></select></label><label>Required reason<textarea value={reason} onChange={e=>setReason(e.target.value)} required/></label><button disabled={busy}>Save changes</button></form></Modal>}
    {editOfficer&&<Modal title="Edit officer account" onClose={()=>setEditOfficer(null)}><form className="login-form" onSubmit={saveOfficer}><label>First name<input value={editOfficer.first_name} onChange={e=>setEditOfficer({...editOfficer,first_name:e.target.value})} required/></label><label>Last name<input value={editOfficer.last_name} onChange={e=>setEditOfficer({...editOfficer,last_name:e.target.value})} required/></label><label>Username<input value={editOfficer.username} onChange={e=>setEditOfficer({...editOfficer,username:e.target.value})} required/></label><label>Email<input type="email" value={editOfficer.email||''} onChange={e=>setEditOfficer({...editOfficer,email:e.target.value})}/></label><label>Employee number<input value={editOfficer.employee_number||''} onChange={e=>setEditOfficer({...editOfficer,employee_number:e.target.value})}/></label><label>Required reason<textarea value={reason} onChange={e=>setReason(e.target.value)} required/></label><button disabled={busy}>Save officer</button></form></Modal>}
    {action&&<Modal title={action.kind==='reset'?'Reset temporary password':`${action.account.is_active?'Deactivate':'Activate'} officer account`} onClose={()=>setAction(null)}><form className="login-form" onSubmit={runAction}><p>This sensitive action is recorded in the audit log.</p><label>Required reason<textarea value={reason} onChange={e=>setReason(e.target.value)} required autoFocus/></label><button disabled={busy}>Confirm action</button></form></Modal>}
  </section>
}
export default AdminDepartmentOfficers
