import { useCallback, useEffect, useMemo, useState } from 'react'
import { API_URL } from '../lib/api.js'
import Modal from './Modal.jsx'
import { buildDepartmentOfficerPayload, departmentStepValid, filterDepartmentOfficers, OFFICER_ROLES, officerStepValid } from '../lib/departmentOfficerAdmin.js'
import { formatManilaDate, formatManilaDateTime } from '../lib/displayFormat.js'

const empty = { departmentName:'', departmentType:'', description:'', departmentStatus:'active', firstName:'', lastName:'', username:'', role:'DISCIPLINE_OFFICE', email:'', employeeNumber:'' }
const blankAssignment = { kind:'permanent', officerId:'', originalOfficerId:'', replacementOfficerId:'', startsAt:'', endsAt:'', reason:'' }
const auth = (token) => ({ Authorization:`Bearer ${token}`, 'Content-Type':'application/json' })
const roleLabel = (role) => role?.replaceAll('_',' ') || 'Officer'
const fullName = (value) => `${value?.first_name || ''} ${value?.last_name || ''}`.trim() || value?.username || 'Officer'

function Directory({ accounts, departments, responsibilities, counts, loading, filters, setFilters, onOpenDepartment, onEditOfficer, onAvailability, onReset, onStatus }) {
  return <>
    <div className="department-summary-grid"><article><b>{counts.departments}</b><span>Total departments</span></article><article><b>{counts.active}</b><span>Active officers</span></article><article><b>{counts.heads}</b><span>Department heads</span></article><article><b>{counts.discipline}</b><span>Discipline officers</span></article></div>
    <section className="table-card">
      <div className="directory-toolbar"><input aria-label="Search directory" placeholder="Search department, officer, or username" value={filters.search} onChange={(event)=>setFilters({...filters,search:event.target.value})}/><select aria-label="Filter by role" value={filters.role} onChange={(event)=>setFilters({...filters,role:event.target.value})}><option value="ALL">All roles</option>{OFFICER_ROLES.map((role)=><option key={role} value={role}>{roleLabel(role)}</option>)}</select><select aria-label="Filter by status" value={filters.status} onChange={(event)=>setFilters({...filters,status:event.target.value})}><option value="ALL">All statuses</option><option value="ACTIVE">Active</option><option value="INACTIVE">Inactive</option></select></div>
      {loading ? <p className="empty-state" role="status">Loading directory...</p> : accounts.length === 0 ? <div className="department-empty"><h4>No matching officer accounts</h4><p>Adjust the filters or create a department and officer.</p></div> : <div className="officer-directory">{accounts.map((account)=>{
        const department = departments.find((item)=>Number(item.id) === Number(account.department_id))
        const current = responsibilities.find((item)=>Number(item.officer_user_id) === Number(account.id) && item.status === 'ACTIVE')
        return <article key={account.id}>
          <div><span className={`status-badge ${account.is_active ? '' : 'status-badge--muted'}`}>{account.is_active ? 'Active account' : 'Inactive account'}</span>{current && <> <span className={`status-badge availability-${String(current.availability_status).toLowerCase()}`}>{current.availability_status}</span></>}<h3>{account.department_name || 'Unassigned department'}</h3><p className="officer-name">{fullName(account)}</p><p>{account.username} · {roleLabel(account.role)}</p></div>
          <dl><div><dt>Email</dt><dd>{account.email || 'Not provided'}</dd></div><div><dt>Employee no.</dt><dd>{account.employee_number || 'Not provided'}</dd></div><div><dt>Assignment</dt><dd>{current?.assignment_type || 'Not assigned'}</dd></div><div><dt>Created</dt><dd>{formatManilaDate(account.created_at)}</dd></div></dl>
          <div className="registration-review-actions">{department && <button type="button" onClick={()=>onOpenDepartment(department)}>Assigned officers</button>}<button type="button" className="secondary-button" onClick={()=>onEditOfficer(account)}>Edit officer</button>{current && <button type="button" className="secondary-button" onClick={()=>onAvailability(account,current)}>Availability</button>}<button type="button" className="secondary-button" onClick={()=>onReset(account)}>Reset password</button><button type="button" className="secondary-button danger-button" onClick={()=>onStatus(account)}>{account.is_active ? 'Deactivate' : 'Activate'}</button></div>
        </article>
      })}</div>}
    </section>
  </>
}

function DepartmentResponsibility({ department, assignments, onAdd, onTransfer, onAvailability, onTransition }) {
  const current = assignments.filter((item)=>item.status === 'ACTIVE')
  return <div className="responsibility-panel">
    <header><div><h3>{department.department_name}</h3><p>{department.description || 'Manage permanent and temporary attendance responsibility.'}</p></div><span className={`status-badge ${department.is_active ? '' : 'status-badge--muted'}`}>{department.is_active ? 'Active department' : 'Inactive department'}</span></header>
    <div className="registration-review-actions"><button type="button" onClick={onAdd}>Add officer</button><button type="button" className="secondary-button" onClick={onTransfer}>Transfer responsibility</button></div>
    <h4>Assigned Officers</h4>
    {current.length === 0 ? <p className="empty-state">No active officer assignment.</p> : <div className="responsibility-list">{current.map((item)=><article key={item.assignment_id}><div><strong>{fullName(item)}</strong><span>{roleLabel(item.role)}</span></div><div className="assignment-badges"><span className={`status-badge availability-${String(item.availability_status).toLowerCase()}`}>{item.availability_status}</span><span className="status-badge">{item.assignment_type}</span></div><dl><div><dt>Starts</dt><dd>{formatManilaDateTime(item.starts_at)}</dd></div><div><dt>Ends</dt><dd>{item.ends_at ? formatManilaDateTime(item.ends_at) : 'Until changed'}</dd></div>{item.original_officer_user_id && <div><dt>Original officer</dt><dd>{`${item.original_first_name || ''} ${item.original_last_name || ''}`.trim()}</dd></div>}<div><dt>Reason</dt><dd>{item.reason}</dd></div></dl><div className="registration-review-actions"><button type="button" className="secondary-button" onClick={()=>onAvailability(item)}>Edit availability</button>{item.assignment_type === 'TEMPORARY' && <button type="button" onClick={()=>onTransition(item)}>Edit assignment</button>}</div></article>)}</div>}
    <details className="assignment-history"><summary>Assignment history ({assignments.length})</summary>{assignments.map((item)=><p key={`history-${item.assignment_id}`}><strong>{fullName(item)}</strong> · {item.assignment_type} · {item.status} · {formatManilaDateTime(item.starts_at)}{item.ends_at ? ` to ${formatManilaDateTime(item.ends_at)}` : ''}</p>)}</details>
  </div>
}

function AdminDepartmentOfficers({ token }) {
  const [tab,setTab]=useState('directory'),[step,setStep]=useState(1),[form,setForm]=useState(empty)
  const [accounts,setAccounts]=useState([]),[departments,setDepartments]=useState([]),[responsibilities,setResponsibilities]=useState([])
  const [loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState('')
  const [secret,setSecret]=useState(null),[selected,setSelected]=useState(null),[editDepartment,setEditDepartment]=useState(null),[editOfficer,setEditOfficer]=useState(null),[action,setAction]=useState(null)
  const [assignmentForm,setAssignmentForm]=useState(null),[availabilityForm,setAvailabilityForm]=useState(null),[transitionForm,setTransitionForm]=useState(null)
  const [filters,setFilters]=useState({search:'',role:'ALL',status:'ALL'}),[reason,setReason]=useState('')

  const load=useCallback(async()=>{setLoading(true);setError('');try{const headers=auth(token);const [a,d,r]=await Promise.all([fetch(`${API_URL}/api/admin/accounts?limit=100`,{headers}),fetch(`${API_URL}/api/admin/departments`,{headers}),fetch(`${API_URL}/api/admin/officer-responsibilities?include_history=true`,{headers})]);const [ad,dd,rd]=await Promise.all([a.json(),d.json(),r.json()]);if(!a.ok)throw new Error(ad.message||'Unable to load officer accounts.');if(!d.ok)throw new Error(dd.message||'Unable to load departments.');if(!r.ok)throw new Error(rd.message||'Unable to load assignments.');setAccounts((ad.accounts||[]).filter((item)=>OFFICER_ROLES.includes(item.role)));setDepartments(dd.departments||[]);setResponsibilities(rd.assignments||[])}catch(e){setError(e.message)}finally{setLoading(false)}},[token])
  useEffect(()=>{load()},[load])
  const visible=useMemo(()=>filterDepartmentOfficers(accounts,departments,filters),[accounts,departments,filters])
  const counts=useMemo(()=>({departments:departments.length,active:accounts.filter((item)=>item.is_active).length,heads:accounts.filter((item)=>item.role==='DEPARTMENT_HEAD').length,discipline:accounts.filter((item)=>item.role==='DISCIPLINE_OFFICE').length}),[accounts,departments])
  const change=(key)=>(event)=>setForm((current)=>({...current,[key]:event.target.value}))
  const request=async(url,options,onDone)=>{setBusy(true);setError('');try{const response=await fetch(`${API_URL}${url}`,{...options,headers:auth(token)});const data=await response.json();if(!response.ok)throw new Error(data.message||'The action could not be completed.');await onDone(data);await load()}catch(e){setError(e.message)}finally{setBusy(false)}}
  const create=(event)=>{event.preventDefault();if(!officerStepValid(form))return;request('/api/admin/accounts/department-officer',{method:'POST',body:JSON.stringify(buildDepartmentOfficerPayload(form))},async(data)=>{setSecret({username:data.account.username,password:data.temporary_password});setForm(empty);setStep(1);setTab('directory')})}
  const saveDepartment=(event)=>{event.preventDefault();if(!reason.trim())return setError('A reason is required.');request(`/api/admin/departments/${editDepartment.id}`,{method:'PATCH',body:JSON.stringify({department_code:editDepartment.department_code,department_name:editDepartment.department_name,department_type:editDepartment.department_type,description:editDepartment.description||'',is_active:editDepartment.is_active,reason:reason.trim()})},async()=>{setEditDepartment(null);setReason('')})}
  const saveOfficer=(event)=>{event.preventDefault();if(!reason.trim())return setError('A reason is required.');request(`/api/admin/accounts/${editOfficer.id}/profile`,{method:'PATCH',body:JSON.stringify({username:editOfficer.username,first_name:editOfficer.first_name,last_name:editOfficer.last_name,employee_number:editOfficer.employee_number||'',email:editOfficer.email||'',reason:reason.trim()})},async()=>{setEditOfficer(null);setReason('')})}
  const runAction=(event)=>{event.preventDefault();if(!reason.trim())return setError('A reason is required.');const reset=action.kind==='reset';request(`/api/admin/accounts/${action.account.id}/${reset?'password-reset':'status'}`,{method:reset?'POST':'PATCH',body:JSON.stringify(reset?{reason:reason.trim()}:{is_active:!action.account.is_active,reason:reason.trim()})},async(data)=>{if(reset)setSecret({username:action.account.username,password:data.temporary_password});setAction(null);setReason('')})}
  const assignmentRequest=(event)=>{event.preventDefault();const value=assignmentForm;if(!value.reason.trim())return setError('A reason is required.');const temporary=value.kind==='temporary';request(`/api/admin/officer-responsibilities/${temporary?'temporary':'permanent'}`,{method:'POST',body:JSON.stringify(temporary?{department_id:value.departmentId,original_officer_id:value.originalOfficerId,replacement_officer_id:value.replacementOfficerId,starts_at:value.startsAt||undefined,ends_at:value.endsAt||undefined,reason:value.reason.trim()}:{department_id:value.departmentId,officer_id:value.officerId,starts_at:value.startsAt||undefined,reason:value.reason.trim()})},async()=>setAssignmentForm(null))}
  const availabilityRequest=(event)=>{event.preventDefault();if(availabilityForm.status!=='AVAILABLE'&&!availabilityForm.reason.trim())return setError('A reason is required when an officer is unavailable or absent.');request(`/api/admin/officer-responsibilities/officers/${availabilityForm.officerId}/availability`,{method:'PATCH',body:JSON.stringify({status:availabilityForm.status,reason:availabilityForm.reason.trim()||undefined})},async()=>setAvailabilityForm(null))}
  const transitionRequest=(event)=>{event.preventDefault();if(!transitionForm.reason.trim()||transitionForm.action==='EXTEND'&&!transitionForm.endsAt)return setError('Complete the action details and required reason.');request(`/api/admin/officer-responsibilities/temporary/${transitionForm.assignmentId}`,{method:'PATCH',body:JSON.stringify({action:transitionForm.action,ends_at:transitionForm.action==='EXTEND'?transitionForm.endsAt:undefined,reason:transitionForm.reason.trim()})},async()=>setTransitionForm(null))}
  const departmentAssignments = assignmentForm ? responsibilities.filter((item)=>Number(item.department_id)===Number(assignmentForm.departmentId)&&item.status==='ACTIVE') : []
  const activeAccounts = accounts.filter((item)=>item.is_active)

  return <section className="department-officer-page" aria-labelledby="department-officer-title">
    <div className="department-welcome"><div><p className="eyebrow">System administration</p><h2 id="department-officer-title">Departments &amp; Officer Accounts</h2><p>Assign multiple accountable officers and manage temporary attendance responsibility.</p></div><div className="department-officer-tabs" role="tablist"><button className={tab==='directory'?'active':''} onClick={()=>setTab('directory')}>Directory</button><button className={tab==='create'?'active':''} onClick={()=>setTab('create')}>Create department &amp; officer</button></div></div>
    {error&&<p className="error-message" role="alert">{error}</p>}
    {tab==='create'&&<Modal title="Add Department / Officer" drawer onClose={()=>setTab('directory')}><section className="department-officer-create"><div className="compact-stepper" aria-label="Creation progress"><button className={step===1?'active':''} onClick={()=>setStep(1)}><b>1</b> Department details</button><span>→</span><button className={step===2?'active':''} disabled={!departmentStepValid(form)} onClick={()=>setStep(2)}><b>2</b> Officer account</button></div>{step===1?<form className="student-form" onSubmit={(event)=>{event.preventDefault();setStep(2)}}><div className="section-heading"><h3>Department details</h3><p>The internal department code is generated safely from its type.</p></div><div className="student-form-grid"><label>Department name<input value={form.departmentName} onChange={change('departmentName')} maxLength="150" required/></label><label>Department type<input value={form.departmentType} onChange={change('departmentType')} maxLength="50" required/></label><label className="full-field">Description (optional)<textarea value={form.description} onChange={change('description')} maxLength="1000"/></label><label>Status<select value={form.departmentStatus} onChange={change('departmentStatus')}><option value="active">Active</option><option value="inactive">Inactive</option></select></label></div><div className="wizard-actions"><span/><button disabled={!departmentStepValid(form)}>Next: Officer account</button></div></form>:<form className="student-form" onSubmit={create}><div className="section-heading"><h3>Officer account</h3><p>A one-time password is generated for first sign-in.</p></div><div className="student-form-grid"><label>First name<input value={form.firstName} onChange={change('firstName')} required/></label><label>Last name<input value={form.lastName} onChange={change('lastName')} required/></label><label>Username<input value={form.username} onChange={change('username')} required/></label><label>Role<select value={form.role} onChange={change('role')}>{OFFICER_ROLES.map((role)=><option key={role} value={role}>{roleLabel(role)}</option>)}</select></label><label>Email (optional)<input type="email" value={form.email} onChange={change('email')}/></label><label>Employee number (optional)<input value={form.employeeNumber} onChange={change('employeeNumber')}/></label></div><div className="wizard-actions"><button type="button" className="secondary-button" onClick={()=>setStep(1)}>Back</button><button disabled={busy||!officerStepValid(form)}>{busy?'Creating securely...':'Create department & officer'}</button></div></form>}</section></Modal>}
    <Directory accounts={visible} departments={departments} responsibilities={responsibilities} counts={counts} loading={loading} filters={filters} setFilters={setFilters} onOpenDepartment={(department)=>setSelected({department})} onEditOfficer={(account)=>{setEditOfficer({...account});setReason('')}} onAvailability={(account,current)=>setAvailabilityForm({officerId:account.id,name:fullName(account),status:current.availability_status||'AVAILABLE',reason:''})} onReset={(account)=>{setAction({kind:'reset',account});setReason('')}} onStatus={(account)=>{setAction({kind:'status',account});setReason('')}} />
    {selected&&<Modal title="Department responsibility" onClose={()=>setSelected(null)} drawer><DepartmentResponsibility department={selected.department} assignments={responsibilities.filter((item)=>Number(item.department_id)===Number(selected.department.id))} onAdd={()=>setAssignmentForm({...blankAssignment,kind:'permanent',departmentId:selected.department.id})} onTransfer={()=>setAssignmentForm({...blankAssignment,kind:'temporary',departmentId:selected.department.id})} onAvailability={(item)=>setAvailabilityForm({officerId:item.officer_user_id,name:fullName(item),status:item.availability_status||'AVAILABLE',reason:''})} onTransition={(item)=>setTransitionForm({assignmentId:item.assignment_id,name:fullName(item),action:'END',endsAt:'',reason:''})}/></Modal>}
    {assignmentForm&&<Modal title={assignmentForm.kind==='temporary'?'Transfer attendance responsibility':'Add officer assignment'} onClose={()=>setAssignmentForm(null)}><form className="login-form" onSubmit={assignmentRequest}>{assignmentForm.kind==='temporary'?<><label>Original absent officer<select value={assignmentForm.originalOfficerId} onChange={(event)=>setAssignmentForm({...assignmentForm,originalOfficerId:event.target.value})} required><option value="">Select original officer</option>{departmentAssignments.filter((item)=>item.assignment_type==='PERMANENT'&&['ABSENT','UNAVAILABLE'].includes(item.availability_status)).map((item)=><option key={item.assignment_id} value={item.officer_user_id}>{fullName(item)} · {item.availability_status}</option>)}</select></label><label>Replacement officer<select value={assignmentForm.replacementOfficerId} onChange={(event)=>setAssignmentForm({...assignmentForm,replacementOfficerId:event.target.value})} required><option value="">Select available replacement</option>{activeAccounts.filter((item)=>Number(item.id)!==Number(assignmentForm.originalOfficerId)&&!responsibilities.some((entry)=>Number(entry.officer_user_id)===Number(item.id)&&entry.status==='ACTIVE'&&entry.availability_status!=='AVAILABLE')).map((item)=><option key={item.id} value={item.id}>{fullName(item)} · {roleLabel(item.role)}</option>)}</select></label></>:<label>Officer<select value={assignmentForm.officerId} onChange={(event)=>setAssignmentForm({...assignmentForm,officerId:event.target.value})} required><option value="">Select active officer</option>{activeAccounts.filter((item)=>!departmentAssignments.some((entry)=>Number(entry.officer_user_id)===Number(item.id)&&entry.assignment_type==='PERMANENT')).map((item)=><option key={item.id} value={item.id}>{fullName(item)} · {roleLabel(item.role)}</option>)}</select></label>}<label>Effective date/time (optional)<input type="datetime-local" value={assignmentForm.startsAt} onChange={(event)=>setAssignmentForm({...assignmentForm,startsAt:event.target.value})}/></label>{assignmentForm.kind==='temporary'&&<label>End date/time (optional)<input type="datetime-local" value={assignmentForm.endsAt} onChange={(event)=>setAssignmentForm({...assignmentForm,endsAt:event.target.value})}/></label>}<label>Required reason<textarea value={assignmentForm.reason} onChange={(event)=>setAssignmentForm({...assignmentForm,reason:event.target.value})} required maxLength="1000"/></label><p>This assignment change is audited and requires confirmation.</p><button disabled={busy}>Confirm assignment</button></form></Modal>}
    {availabilityForm&&<Modal title={`Officer availability — ${availabilityForm.name}`} onClose={()=>setAvailabilityForm(null)}><form className="login-form" onSubmit={availabilityRequest}><label>Availability<select value={availabilityForm.status} onChange={(event)=>setAvailabilityForm({...availabilityForm,status:event.target.value})}><option value="AVAILABLE">Available</option><option value="UNAVAILABLE">Unavailable</option><option value="ABSENT">Absent</option></select></label><label>Reason {availabilityForm.status==='AVAILABLE'?'(optional)':'(required)'}<textarea value={availabilityForm.reason} onChange={(event)=>setAvailabilityForm({...availabilityForm,reason:event.target.value})} required={availabilityForm.status!=='AVAILABLE'} maxLength="1000"/></label><button disabled={busy}>Save availability</button></form></Modal>}
    {transitionForm&&<Modal title={`Edit temporary assignment — ${transitionForm.name}`} onClose={()=>setTransitionForm(null)}><form className="login-form" onSubmit={transitionRequest}><label>Action<select value={transitionForm.action} onChange={(event)=>setTransitionForm({...transitionForm,action:event.target.value})}><option value="END">End and restore responsibility</option><option value="EXTEND">Extend assignment</option><option value="CANCEL">Cancel assignment</option></select></label>{transitionForm.action==='EXTEND'&&<label>New end date/time<input type="datetime-local" value={transitionForm.endsAt} onChange={(event)=>setTransitionForm({...transitionForm,endsAt:event.target.value})} required/></label>}<label>Required reason<textarea value={transitionForm.reason} onChange={(event)=>setTransitionForm({...transitionForm,reason:event.target.value})} required maxLength="1000"/></label><button disabled={busy}>Confirm action</button></form></Modal>}
    {secret&&<Modal title="One-time temporary password" onClose={()=>setSecret(null)}><div className="one-time-secret" role="alert"><p>Copy this now. It is never stored or shown again.</p><label>Username<code>{secret.username}</code></label><label>Temporary password<code>{secret.password}</code></label><button onClick={()=>navigator.clipboard?.writeText(secret.password)}>Copy password</button><button className="secondary-button" onClick={()=>setSecret(null)}>I stored it securely</button></div></Modal>}
    {editDepartment&&<Modal title="Edit department" onClose={()=>setEditDepartment(null)}><form className="login-form" onSubmit={saveDepartment}><label>Name<input value={editDepartment.department_name} onChange={(event)=>setEditDepartment({...editDepartment,department_name:event.target.value})} required/></label><label>Type<input value={editDepartment.department_type||''} onChange={(event)=>setEditDepartment({...editDepartment,department_type:event.target.value.toUpperCase()})} required/></label><label>Description<textarea value={editDepartment.description||''} onChange={(event)=>setEditDepartment({...editDepartment,description:event.target.value})}/></label><label>Status<select value={editDepartment.is_active?'active':'inactive'} onChange={(event)=>setEditDepartment({...editDepartment,is_active:event.target.value==='active'})}><option value="active">Active</option><option value="inactive">Inactive</option></select></label><label>Required reason<textarea value={reason} onChange={(event)=>setReason(event.target.value)} required/></label><button disabled={busy}>Save changes</button></form></Modal>}
    {editOfficer&&<Modal title="Edit officer account" onClose={()=>setEditOfficer(null)}><form className="login-form" onSubmit={saveOfficer}><label>First name<input value={editOfficer.first_name} onChange={(event)=>setEditOfficer({...editOfficer,first_name:event.target.value})} required/></label><label>Last name<input value={editOfficer.last_name} onChange={(event)=>setEditOfficer({...editOfficer,last_name:event.target.value})} required/></label><label>Username<input value={editOfficer.username} onChange={(event)=>setEditOfficer({...editOfficer,username:event.target.value})} required/></label><label>Email<input type="email" value={editOfficer.email||''} onChange={(event)=>setEditOfficer({...editOfficer,email:event.target.value})}/></label><label>Employee number<input value={editOfficer.employee_number||''} onChange={(event)=>setEditOfficer({...editOfficer,employee_number:event.target.value})}/></label><label>Required reason<textarea value={reason} onChange={(event)=>setReason(event.target.value)} required/></label><button disabled={busy}>Save officer</button></form></Modal>}
    {action&&<Modal title={action.kind==='reset'?'Reset temporary password':`${action.account.is_active?'Deactivate':'Activate'} officer account`} onClose={()=>setAction(null)}><form className="login-form" onSubmit={runAction}><p>This sensitive action is recorded in the audit log.</p><label>Required reason<textarea value={reason} onChange={(event)=>setReason(event.target.value)} required autoFocus/></label><button disabled={busy}>Confirm action</button></form></Modal>}
  </section>
}

export default AdminDepartmentOfficers
