import { useCallback, useEffect, useState } from 'react'
import { API_URL } from '../lib/api.js'
import { resolveDepartmentId } from '../lib/departmentAccounts.js'

function DepartmentAccounts({ token }) {
  const [accounts,setAccounts]=useState([]),[departments,setDepartments]=useState([]),[form,setForm]=useState({username:'',department_name:''})
  const [secret,setSecret]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[action,setAction]=useState(null),[reason,setReason]=useState('')
  const headers={Authorization:`Bearer ${token}`}
  const load=useCallback(async()=>{const requestHeaders={Authorization:`Bearer ${token}`};setError('');try{const [accountsResponse,optionsResponse]=await Promise.all([fetch(`${API_URL}/api/department-accounts`,{headers:requestHeaders}),fetch(`${API_URL}/api/department-accounts/options`,{headers:requestHeaders})]);const accountsData=await accountsResponse.json(),optionsData=await optionsResponse.json();if(!accountsResponse.ok)throw new Error(accountsData.message||'Unable to load Department Accounts.');if(!optionsResponse.ok)throw new Error(optionsData.message||'Unable to load departments.');setAccounts(accountsData.accounts||[]);setDepartments(optionsData.departments||[])}catch(e){setError(e.message)}},[token])
  useEffect(()=>{load()},[load])
  const create=async(event)=>{event.preventDefault();setBusy(true);setError('');try{const departmentId=resolveDepartmentId(departments,form.department_name);if(!departmentId)throw new Error('Enter an existing active department. Create a new department in Departments first.');const response=await fetch(`${API_URL}/api/department-accounts`,{method:'POST',headers:{...headers,'Content-Type':'application/json'},body:JSON.stringify({username:form.username,department_id:departmentId})});const data=await response.json();if(!response.ok)throw new Error(data.message||'Unable to create Department Account.');setSecret({username:data.account.username,password:data.temporary_password});setForm({username:'',department_name:''});await load()}catch(e){setError(e.message)}finally{setBusy(false)}}
  const apply=async(event)=>{event.preventDefault();if(!reason.trim())return;setBusy(true);setError('');try{const reset=action.type==='reset';const response=await fetch(`${API_URL}/api/department-accounts/${action.account.id}/${reset?'password-reset':'status'}`,{method:reset?'POST':'PATCH',headers:{...headers,'Content-Type':'application/json'},body:JSON.stringify(reset?{reason:reason.trim()}:{is_active:!action.account.is_active,reason:reason.trim()})});const data=await response.json();if(!response.ok)throw new Error(data.message||'Unable to update Department Account.');if(reset)setSecret({username:action.account.username,password:data.temporary_password});setAction(null);setReason('');await load()}catch(e){setError(e.message)}finally{setBusy(false)}}
  return <section className="registration-review-page"><div className="department-welcome"><div><p className="eyebrow">Discipline Office</p><h2>Department Accounts</h2><p>Issue one shared operational account per department for QR time-in, time-out, and service-result submission.</p></div><span className="status-badge">{accounts.length} accounts</span></div>
    {secret&&<section className="table-card registration-pending" role="alert"><h3>Give these credentials privately</h3><p>The temporary password is shown once. The department must replace it at first sign in.</p><dl><div><dt>Username</dt><dd>{secret.username}</dd></div><div><dt>Temporary password</dt><dd><code>{secret.password}</code></dd></div></dl><button type="button" onClick={()=>setSecret(null)}>I stored it securely</button></section>}
    {error&&<p className="error-message" role="alert">{error}</p>}
    <section className="table-card form-card"><h3>Create Department Account</h3><form className="student-form" onSubmit={create}><div className="student-form-grid"><label>Account username<input value={form.username} onChange={e=>setForm({...form,username:e.target.value})} placeholder="library.department" required/></label><label>Department<input list="active-department-options" value={form.department_name} onChange={e=>setForm({...form,department_name:e.target.value})} placeholder="Type or choose a department" autoComplete="off" required/><datalist id="active-department-options">{departments.map(item=><option key={item.id} value={item.department_name}/>)}</datalist><span>Enter an existing active department. Add new departments from the Departments page first.</span></label></div><button disabled={busy}>{busy?'Creating…':'Create and generate password'}</button></form></section>
    <section className="table-card"><div className="table-header"><h3>Account directory</h3></div><div className="registration-review-list">{accounts.map(account=><article key={account.id}><div className="registration-review-heading"><div><h4>{account.department_name}</h4><p>{account.username}</p></div><span className="status-badge">{account.is_active?'Active':'Access removed'}</span></div><dl><div><dt>First sign-in password change</dt><dd>{account.must_change_password?'Required':'Complete'}</dd></div></dl><div className="registration-review-actions"><button type="button" className={account.is_active?'danger-button':''} onClick={()=>{setAction({type:'status',account});setReason('')}}>{account.is_active?'Remove portal access':'Restore portal access'}</button><button type="button" className="secondary-button" onClick={()=>{setAction({type:'reset',account});setReason('')}}>Reset password</button></div></article>)}</div></section>
    {action&&<section className="table-card"><h3>{action.type==='reset'?'Reset temporary password':action.account.is_active?'Remove Department Account access':'Restore Department Account access'}</h3>{action.type==='status'&&<p>{action.account.is_active?'This closes existing sessions but preserves DTR, service, and audit records.':'After restoring access, reset the password if the department needs new credentials.'}</p>}<form className="login-form" onSubmit={apply}><label>Required reason<textarea value={reason} onChange={e=>setReason(e.target.value)} required maxLength="1000"/></label><div className="registration-review-actions"><button className={action.type==='status'&&action.account.is_active?'danger-button':''} disabled={busy}>Confirm</button><button type="button" className="secondary-button" onClick={()=>setAction(null)}>Cancel</button></div></form></section>}
  </section>
}
export default DepartmentAccounts
