import { useCallback, useEffect, useState } from 'react'
import { API_URL } from '../lib/api.js'

function GoogleDepartmentRegistrationReview({ token }) {
  const [items,setItems]=useState([]), [departments,setDepartments]=useState([]), [loading,setLoading]=useState(true), [error,setError]=useState('')
  const [forms,setForms]=useState({}), [busy,setBusy]=useState(null)
  const load=useCallback(async()=>{ setLoading(true);setError('');try{const response=await fetch(`${API_URL}/api/admin/google-department-registrations?status=PENDING`,{headers:{Authorization:`Bearer ${token}`}});const data=await response.json();if(!response.ok||data.success===false)throw new Error(data.message||'Unable to load requests.');setItems(data.registrations||[]);setDepartments(data.departments||[])}catch(e){setError(e.message)}finally{setLoading(false)}},[token])
  useEffect(()=>{load()},[load])
  const update=(id,key,value)=>setForms({...forms,[id]:{...forms[id],[key]:value}})
  const review=async(item,decision)=>{const form=forms[item.id]||{};if(!String(form.reason||'').trim()||(decision==='approve'&&!form.departmentId)){setError('Enter a reason and select an active department before approval.');return}setBusy(item.id);setError('');try{const response=await fetch(`${API_URL}/api/admin/google-department-registrations/${item.id}/${decision}`,{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({reason:form.reason,department_id:decision==='approve'?Number(form.departmentId):undefined})});const data=await response.json();if(!response.ok||data.success===false)throw new Error(data.message||'Unable to review request.');setItems(items.filter(x=>x.id!==item.id))}catch(e){setError(e.message)}finally{setBusy(null)}}
  return <section className="registration-review-page"><div className="department-welcome"><div><p className="eyebrow">Account verification</p><h2>Department officer registrations</h2><p>Verify employment and assign exactly one active department before granting access.</p></div><span className="status-badge">{items.length} pending</span></div>{error&&<p className="error-message" role="alert">{error}</p>}{loading?<section className="table-card"><p>Loading requests…</p></section>:items.length===0?<section className="table-card"><div className="department-empty"><h4>No pending requests</h4></div></section>:<div className="registration-review-list">{items.map(item=><article className="table-card" key={item.id}><div className="registration-review-heading"><div><h3>{item.officer_first_name} {item.officer_last_name}</h3><p>{item.google_email}</p></div><span className="status-badge">{item.requested_department_type.replaceAll('_',' ')}</span></div><dl><div><dt>Requested office</dt><dd>{item.requested_department_name}</dd></div><div><dt>Employee number</dt><dd>{item.employee_number||'Not provided'}</dd></div><div><dt>Applicant note</dt><dd>{item.applicant_note||'None'}</dd></div></dl><label>Assign active department<select value={forms[item.id]?.departmentId||''} onChange={e=>update(item.id,'departmentId',e.target.value)} disabled={busy===item.id}><option value="">Select department</option>{departments.map(d=><option value={d.id} key={d.id}>{d.department_name}</option>)}</select></label><label>Review reason<textarea maxLength="1000" value={forms[item.id]?.reason||''} onChange={e=>update(item.id,'reason',e.target.value)} disabled={busy===item.id}/></label><div className="registration-review-actions"><button onClick={()=>review(item,'approve')} disabled={busy===item.id}>Approve and assign</button><button className="danger-button" onClick={()=>review(item,'reject')} disabled={busy===item.id}>Reject request</button></div></article>)}</div>}</section>
}
export default GoogleDepartmentRegistrationReview
