import {useCallback,useEffect,useState} from 'react'
import {API_URL} from '../lib/api.js'
import {formatManilaDateTime} from '../lib/displayFormat.js'
import Modal from './Modal.jsx'

const label=(value='')=>String(value).replaceAll('_',' ').toLowerCase().replace(/\b\w/g,(c)=>c.toUpperCase())
const read=async(response)=>{const data=await response.json().catch(()=>({}));if(!response.ok){const error=new Error(data.error?.message||'The action could not be completed.');error.code=data.error?.code;throw error}return data}

export default function HighRiskActionPanel({token,role,user}){
 const [requests,setRequests]=useState([]),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[dialog,setDialog]=useState(null),[reason,setReason]=useState(''),[password,setPassword]=useState('')
 const load=useCallback(async()=>{try{const response=await fetch(`${API_URL}/api/high-risk-actions`,{headers:{Authorization:`Bearer ${token}`}});setRequests((await read(response)).requests||[])}catch(e){setError(e.message)}},[token])
 useEffect(()=>{load()},[load])
 const decide=async(event)=>{event.preventDefault();setBusy(true);setError('');try{const response=await fetch(`${API_URL}/api/high-risk-actions/${dialog.request.id}/decision`,{method:'PATCH',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({approve:dialog.action==='approve',reason})});await read(response);setNotice(`Request #${dialog.request.id} ${dialog.action==='approve'?'approved':'rejected'}.`);setDialog(null);setReason('');await load()}catch(e){setError(e.message)}finally{setBusy(false)}}
 const execute=async(event)=>{event.preventDefault();setBusy(true);setError('');try{const request=dialog.request;let response=await fetch(`${API_URL}/api/high-risk-actions/step-up`,{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({password,action_type:request.action_type,target_type:request.target_type,target_id:request.target_id})});const step=(await read(response)).step_up;response=await fetch(`${API_URL}/api/high-risk-actions/${request.id}/execute`,{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({step_up_token:step.token})});const data=await read(response);setNotice(`Request #${request.id} executed.`);if(data.result?.temporary_password)setNotice(`Recovery executed. Copy the temporary password now: ${data.result.temporary_password}`);setDialog(null);setPassword('');await load()}catch(e){if(e.code==='INVALID_CREDENTIALS')setPassword('');setError(e.code==='INVALID_CREDENTIALS'?`Enter the current password for the signed-in account ${user?.username||''}.`.trim():e.message)}finally{setBusy(false)}}
 return <section className="system-dashboard"><header className="management-page-header"><div><span className="page-breadcrumb">Two-person control</span><h2>{role==='SYSTEM_ADMIN'?'My high-risk actions':'High-risk approval queue'}</h2><p>{role==='SYSTEM_ADMIN'?'Track approvals and execute approved actions after confirming your password.':'Review requests independently. Approval expires after 15 minutes.'}</p></div><span className="status-badge">{requests.filter((r)=>r.status==='PENDING').length} pending</span></header>{error&&<p className="error-message" role="alert">{error}</p>}{notice&&<p className="success-message" role="status">{notice}</p>}<section className="table-card"><div className="table-wrap"><table><thead><tr><th>Request</th><th>Action and target</th><th>Reason</th><th>Status</th><th>Decision / expiry</th><th>Actions</th></tr></thead><tbody>{requests.map((request)=><tr key={request.id}><td><strong>#{request.id}</strong><br/><small>{formatManilaDateTime(request.created_at)}</small></td><td><strong>{label(request.action_type)}</strong><br/><small>{request.request_summary?.target||request.target_id}</small></td><td>{request.reason}</td><td><span className="status-badge">{request.status}</span></td><td>{request.approval_expires_at?formatManilaDateTime(request.approval_expires_at):request.decision_reason||'Awaiting review'}</td><td>{role==='DISCIPLINE_ADMIN'&&request.status==='PENDING'&&<div className="action-row"><button onClick={()=>setDialog({request,action:'approve'})}>Approve</button><button className="secondary-button" onClick={()=>setDialog({request,action:'reject'})}>Reject</button></div>}{role==='SYSTEM_ADMIN'&&request.status==='APPROVED'&&<button onClick={()=>setDialog({request,action:'execute'})}>Execute</button>}</td></tr>)}{!requests.length&&<tr><td colSpan="6"><p className="empty-state">No high-risk action requests.</p></td></tr>}</tbody></table></div></section>{dialog&&<Modal title={`${label(dialog.action)} request #${dialog.request.id}`} onClose={()=>setDialog(null)} dirty={Boolean(reason||password)}><form onSubmit={dialog.action==='execute'?execute:decide}><p><strong>{label(dialog.request.action_type)}</strong> · {dialog.request.request_summary?.target}</p>{dialog.action==='execute'?<label><span>Current password</span><input autoFocus required type="password" autoComplete="current-password" value={password} onChange={(e)=>setPassword(e.target.value)}/></label>:<label><span>Decision reason</span><textarea autoFocus required minLength="10" maxLength="1000" value={reason} onChange={(e)=>setReason(e.target.value)}/></label>}<div className="support-decision-actions"><button type="button" className="secondary-button" onClick={()=>setDialog(null)}>Cancel</button><button disabled={busy||(dialog.action==='execute'?!password:reason.trim().length<10)}>{busy?'Saving…':label(dialog.action)}</button></div></form></Modal>}</section>
}
