import { useCallback, useEffect, useRef, useState } from 'react'
import { API_URL } from '../lib/api.js'
import { unreadMessageCount } from '../lib/messageUnread.js'

function MessagesPage({token,role,students=[],onUnreadChange,realtimeSocket}){
 const [conversations,setConversations]=useState([]),[selected,setSelected]=useState(null),[messages,setMessages]=useState([])
 const [form,setForm]=useState({student_id:'',subject:'',message:''}),[reply,setReply]=useState(''),[error,setError]=useState('')
 const [threadError,setThreadError]=useState(''),[threadLoading,setThreadLoading]=useState(false)
 const selectedRef=useRef(null)
 const isStudent=role==='STUDENT',headers={Authorization:`Bearer ${token}`,'Content-Type':'application/json'}
 const load=useCallback(async()=>{const response=await fetch(`${API_URL}/api/messages/conversations`,{headers:{Authorization:`Bearer ${token}`}}),data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.message||'Unable to load conversations.');const items=data.conversations||[];setConversations(items);onUnreadChange?.(unreadMessageCount(items))},[token,onUnreadChange])
 useEffect(()=>{load().catch(e=>setError(e.message))},[load])
 useEffect(()=>{selectedRef.current=selected},[selected])
 const refreshThread=useCallback(async conversation=>{const response=await fetch(`${API_URL}/api/messages/conversations/${conversation.id}`,{headers:{Authorization:`Bearer ${token}`}}),data=await response.json().catch(()=>({}));if(response.ok){setSelected(data.conversation);setMessages(data.messages||[])}},[token])
 useEffect(()=>{if(!realtimeSocket)return undefined;const refresh=()=>{load().catch(e=>setError(e.message));if(selectedRef.current)refreshThread(selectedRef.current).catch(e=>setThreadError(e.message))};realtimeSocket.on('messages:changed',refresh);return()=>realtimeSocket.off('messages:changed',refresh)},[load,realtimeSocket,refreshThread])
 const open=async conversation=>{setError('');setThreadError('');setSelected(conversation);setMessages([]);setThreadLoading(true);try{const response=await fetch(`${API_URL}/api/messages/conversations/${conversation.id}`,{headers}),data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.message||'Unable to open conversation.');setSelected(data.conversation);setMessages(data.messages||[]);fetch(`${API_URL}/api/messages/conversations/${conversation.id}/read`,{method:'PATCH',headers,body:'{}'}).then(readResponse=>{if(readResponse.ok)load().catch(()=>{})}).catch(()=>{})}catch(openError){setThreadError(openError.message)}finally{setThreadLoading(false)}}
 const create=async event=>{event.preventDefault();setError('');const body=isStudent?{subject:form.subject,message:form.message}:form,response=await fetch(`${API_URL}/api/messages/conversations`,{method:'POST',headers,body:JSON.stringify(body)}),data=await response.json().catch(()=>({}));if(!response.ok)return setError(data.message||'Unable to create conversation.');setForm({student_id:'',subject:'',message:''});await load();await open(data.conversation)}
 const send=async event=>{event.preventDefault();setError('');const response=await fetch(`${API_URL}/api/messages/conversations/${selected.id}/messages`,{method:'POST',headers,body:JSON.stringify({message:reply})}),data=await response.json().catch(()=>({}));if(!response.ok)return setThreadError(data.message||'Unable to send message.');setReply('');await open(selected)}
 return <div className="messages-page"><section className="department-welcome"><div><p className="eyebrow">Secure communication</p><h2>Messages</h2><p>Text-only conversations between students and authorized school personnel.</p></div></section>
  {error&&<p className="error-message" role="alert">{error}</p>}
  <form className="table-card message-compose" onSubmit={create}><h3>New conversation</h3>{!isStudent&&<label>Student<select required value={form.student_id} onChange={e=>setForm({...form,student_id:e.target.value})}><option value="">Select student</option>{students.map(student=><option key={student.id} value={student.id}>{student.student_number} - {student.first_name} {student.last_name}</option>)}</select></label>}<label>Subject<input required maxLength="200" value={form.subject} onChange={e=>setForm({...form,subject:e.target.value})}/></label><label>Message<textarea required maxLength="2000" value={form.message} onChange={e=>setForm({...form,message:e.target.value})}/></label><button>Start conversation</button></form>
  <div className="message-layout"><section className="table-card message-conversations"><h3>Conversations</h3>{conversations.length===0?<p>No conversations yet.</p>:conversations.map(conversation=><button type="button" key={conversation.id} aria-pressed={selected?.id===conversation.id} className={selected?.id===conversation.id?'active':''} onClick={()=>open(conversation)}><strong>{conversation.subject}</strong><span>{conversation.student_number} · {conversation.first_name} {conversation.last_name}</span>{Number(conversation.unread_count)>0&&<b>{conversation.unread_count}</b>}</button>)}</section>
   <section className="table-card message-thread" aria-live="polite">{!selected?<p>Select a conversation.</p>:<><h3>{selected.subject}</h3>{threadLoading?<p className="empty-state">Loading replies…</p>:threadError?<div><p className="error-message" role="alert">{threadError}</p><button type="button" className="secondary-button" onClick={()=>open(selected)}>Try again</button></div>:<><div>{messages.length===0?<p>No replies yet.</p>:messages.map(message=><article key={message.id} className={message.sent_by_me?'mine':''}><strong>{message.sent_by_me?'You':message.sender_name} · {message.sender_role.replaceAll('_',' ')}</strong><p>{message.message_text}</p><time>{new Date(message.created_at).toLocaleString()}</time></article>)}</div><form onSubmit={send}><textarea required maxLength="2000" value={reply} onChange={e=>setReply(e.target.value)}/><button>Send reply</button></form></>}</>}</section></div>
  <p className="scope-note">Messages are append-only. Do not send passwords, authentication codes, or Google credentials.</p></div>
}
export default MessagesPage
