import { useState } from 'react'
import { changePassword } from '../lib/api.js'

function PasswordChangeRequired({ token, onSession, onLogout }) {
  const [form,setForm]=useState({currentPassword:'',newPassword:'',confirmPassword:''})
  const [busy,setBusy]=useState(false),[error,setError]=useState('')
  const submit=async(event)=>{event.preventDefault();setError('');if(form.newPassword!==form.confirmPassword)return setError('New password confirmation does not match.');setBusy(true);try{const session=await changePassword({token,currentPassword:form.currentPassword,newPassword:form.newPassword});setForm({currentPassword:'',newPassword:'',confirmPassword:''});onSession(session)}catch(e){setError(e.message)}finally{setBusy(false)}}
  return <section className="login-page" aria-labelledby="password-change-title"><div className="login-intro"><span className="login-kicker">Account security</span><h2>Protect your individual school account.</h2><p>Your temporary password must be replaced before you can access portal records.</p></div><div className="login-card auth-card"><div className="card-header auth-card-header"><div><span className="badge">Required action</span><h3 id="password-change-title">Create a new password</h3><p>Use 12–128 characters with uppercase, lowercase, number, and symbol.</p></div></div><form className="login-form" onSubmit={submit}><label>Current or temporary password<input type="password" autoComplete="current-password" value={form.currentPassword} onChange={e=>setForm({...form,currentPassword:e.target.value})} disabled={busy} required autoFocus/></label><label>New password<input type="password" autoComplete="new-password" minLength="12" maxLength="128" value={form.newPassword} onChange={e=>setForm({...form,newPassword:e.target.value})} disabled={busy} required/></label><label>Confirm new password<input type="password" autoComplete="new-password" minLength="12" maxLength="128" value={form.confirmPassword} onChange={e=>setForm({...form,confirmPassword:e.target.value})} disabled={busy} required/></label>{error&&<p className="error-message" role="alert">{error}</p>}<button disabled={busy}>{busy?'Changing password…':'Change password and continue'}</button><button type="button" className="secondary-button" onClick={onLogout} disabled={busy}>Sign out</button></form></div></section>
}
export default PasswordChangeRequired
