import { useCallback, useEffect, useState } from 'react'
import { API_URL } from '../lib/api.js'

function ServiceResultReview({token,onChanged}){
 const [results,setResults]=useState([]),[error,setError]=useState(''),[active,setActive]=useState(null),[notes,setNotes]=useState(''),[busy,setBusy]=useState(false)
 const load=useCallback(async()=>{try{const response=await fetch(`${API_URL}/api/community-service/results/pending`,{headers:{Authorization:`Bearer ${token}`}}),data=await response.json();if(!response.ok)throw new Error(data.message||'Unable to load pending results.');setResults(data.results||[])}catch(e){setError(e.message)}},[token])
 useEffect(()=>{load()},[load])
 const review=async(event)=>{event.preventDefault();setBusy(true);setError('');try{const response=await fetch(`${API_URL}/api/community-service/results/${active.id}/review`,{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({decision:active.decision,review_notes:notes.trim()})}),data=await response.json();if(!response.ok)throw new Error(data.message||'Unable to review result.');setActive(null);setNotes('');await load();onChanged?.()}catch(e){setError(e.message)}finally{setBusy(false)}}
 return <section className="table-card"><div className="table-header"><div><h3>Pending department service results</h3><p>Worked time is credited only after Discipline Office approval.</p></div><span>{results.length} pending</span></div>{error&&<p className="error-message" role="alert">{error}</p>}{results.length===0?<p className="empty-state">No service results are waiting for review.</p>:<div className="registration-review-list">{results.map(item=><article key={item.id}><div className="registration-review-heading"><div><h4>{item.student_number} — {item.first_name} {item.last_name}</h4><p>{item.department_name} · {item.worked_minutes} worked minutes</p></div><span className="status-badge">{item.service_condition?.replaceAll('_',' ')}</span></div><p>{item.result_notes||'No result note supplied.'}</p><div className="registration-review-actions"><button type="button" onClick={()=>setActive({id:item.id,decision:'APPROVE'})}>Approve credit</button><button type="button" className="secondary-button" onClick={()=>setActive({id:item.id,decision:'REJECT'})}>Reject</button></div></article>)}</div>}{active&&<form className="login-form" onSubmit={review}><label>Required review note<textarea value={notes} onChange={e=>setNotes(e.target.value)} required maxLength="1000"/></label><div className="registration-review-actions"><button disabled={busy}>Confirm {active.decision.toLowerCase()}</button><button type="button" className="secondary-button" onClick={()=>setActive(null)}>Cancel</button></div></form>}</section>
}
export default ServiceResultReview
