import { useEffect, useRef, useState } from 'react'
import { completeStudentOnboarding, linkStudentGoogle, requestStudentGoogleEmail, verifyStudentGoogleEmail } from '../lib/api.js'
import { googleButtonConfiguration, googleIdentityConfiguration, isGoogleClientConfigured, loadGoogleIdentityServices, readGoogleCredential } from '../lib/googleIdentity.js'
import { normalizePhilippinePhone } from '../lib/phone.js'
import OnboardingProgress from './OnboardingProgress.jsx'
import PhoneInput from './PhoneInput.jsx'
import ProgramSelect from './ProgramSelect.jsx'
import OtpInput from './OtpInput.jsx'

const emptyProfile={academicLevel:'COLLEGE',program:'',section:'',yearLevel:'',phoneNumber:'',guardianName:'',guardianRelationship:'',guardianPhoneNumber:''}

export default function StudentOnboarding({user,clientId,onSession,onLogout}) {
  const step=user?.onboarding_step||'GOOGLE',googleStage=user?.google_onboarding_stage||'EMAIL',buttonRef=useRef(null),callbackRef=useRef(null)
  const [form,setForm]=useState(emptyProfile),[email,setEmail]=useState(user?.onboarding_google_email||''),[code,setCode]=useState(''),[editingEmail,setEditingEmail]=useState(false),[cooldown,setCooldown]=useState(0),[busy,setBusy]=useState(false),[error,setError]=useState('')
  const yearLevelOptions=form.academicLevel==='COLLEGE'?[[1,'1st Level'],[2,'2nd Level'],[3,'3rd Level'],[4,'4th Level']]:[[11,'Grade 11'],[12,'Grade 12']]
  callbackRef.current=async(response)=>{const credential=readGoogleCredential(response);if(!credential)return setError('Google did not return a valid sign-in response. Try again.');setBusy(true);setError('');try{const data=await linkStudentGoogle(credential);onSession(data)}catch(e){setError(e.message)}finally{setBusy(false)}}
  useEffect(()=>{if(step!=='GOOGLE'||googleStage!=='OAUTH'||!isGoogleClientConfigured(clientId))return undefined;let active=true,node=buttonRef.current;loadGoogleIdentityServices().then((google)=>{if(!active||!node)return;node.replaceChildren();google.initialize(googleIdentityConfiguration({clientId,callback:(response)=>callbackRef.current?.(response)}));google.renderButton(node,googleButtonConfiguration({width:node.clientWidth}))}).catch((e)=>active&&setError(e.message));return()=>{active=false;if(node)node.replaceChildren()}},[clientId,step,googleStage])
  useEffect(()=>{if(!cooldown)return undefined;const timer=window.setInterval(()=>setCooldown((value)=>Math.max(0,value-1)),1000);return()=>window.clearInterval(timer)},[cooldown])
  const change=(key)=>(event)=>setForm((current)=>({...current,[key]:event.target.value}))
  const changeAcademicLevel=(event)=>{const academicLevel=event.target.value;setForm((current)=>({...current,academicLevel,program:academicLevel==='COLLEGE'?current.program:'',yearLevel:''}));setError('')}
  const submit=async(event)=>{event.preventDefault();setBusy(true);setError('');const profile={...(form.academicLevel==='SENIOR_HIGH_SCHOOL'?{academic_level:form.academicLevel}:{}),program:form.academicLevel==='COLLEGE'?form.program:null,section:form.section.trim(),year_level:Number(form.yearLevel),phone_number:normalizePhilippinePhone(form.phoneNumber),guardian_name:form.guardianName,guardian_relationship:form.guardianRelationship,guardian_phone_number:normalizePhilippinePhone(form.guardianPhoneNumber)};try{const data=await completeStudentOnboarding(profile);setForm(emptyProfile);onSession(data)}catch(e){setError(e.message)}finally{setBusy(false)}}
  const sendCode=async(event)=>{event?.preventDefault();setBusy(true);setError('');try{const data=await requestStudentGoogleEmail(email.trim());setEditingEmail(false);setCode('');setCooldown(60);onSession(data)}catch(e){setError(e.message)}finally{setBusy(false)}}
  const verifyCode=async(event)=>{event.preventDefault();setBusy(true);setError('');try{const data=await verifyStudentGoogleEmail(code);setCode('');onSession(data)}catch(e){setError(e.message)}finally{setBusy(false)}}
  const googleSubsteps=['EMAIL','OTP','OAUTH'];
  const googlePanel=()=> <section className="onboarding-stage"><div><h2>Bind your Google account</h2><p>Confirm the inbox first, then sign in with the same Google account.</p></div><ol className="google-onboarding-progress" aria-label="Google account verification progress">{['Email','Verification code','Google sign-in'].map((label,index)=><li key={label} className={googleSubsteps.indexOf(googleStage)>index?'complete':googleStage===googleSubsteps[index]?'current':''}><span>{googleSubsteps.indexOf(googleStage)>index?'✓':index+1}</span>{label}</li>)}</ol>{(googleStage==='EMAIL'||editingEmail)?<form onSubmit={sendCode} className="google-email-form"><label>Google account email<input type="email" value={email} onChange={(event)=>setEmail(event.target.value)} autoComplete="email" placeholder="@gmail.com" required autoFocus/></label><p>Use personal Gmail only. Microsoft Entra ID/School emails (@sti.edu.ph) are not supported yet.</p><button disabled={busy}>{busy?'Sending code…':'Send verification code'}</button></form>:googleStage==='OTP'?<form onSubmit={verifyCode} className="google-email-form"><p>Enter the six-digit code sent to <strong>{user.onboarding_google_email}</strong>.</p><OtpInput id="google-email-code" label="Verification code" value={code} onChange={setCode} disabled={busy} invalid={Boolean(error)} describedBy={error?'onboarding-error':undefined} autoFocus/><button disabled={busy||code.length!==6}>{busy?'Verifying…':'Verify email'}</button><div className="google-email-actions"><button type="button" className="secondary-button" onClick={()=>sendCode()} disabled={busy||cooldown>0}>{cooldown?`Resend in ${cooldown}s`:'Resend code'}</button><button type="button" className="secondary-button" onClick={()=>{setEditingEmail(true);setEmail(user.onboarding_google_email||'');setError('')}} disabled={busy}>Use another email</button></div></form>:<div className="google-oauth-confirm"><p>Verified: <strong>{user.onboarding_google_email}</strong></p><p>Continue with this exact Google account to finish linking it.</p>{isGoogleClientConfigured(clientId)?<><div ref={buttonRef} className="google-button" aria-busy={busy}/>{busy&&<p role="status">Verifying your Google account…</p>}</>:<p className="error-message" role="alert">Google account setup is unavailable. Ask the Discipline Office to check the Google client configuration.</p>}<button type="button" className="secondary-button" onClick={()=>{setEditingEmail(true);setEmail(user.onboarding_google_email||'')}} disabled={busy}>Use another email</button></div>}</section>
  return <main className="student-onboarding" id="main-content">
    <section className="student-onboarding-card" aria-labelledby="student-onboarding-title">
      <header><span className="badge">Required account setup</span><h1 id="student-onboarding-title">Finish securing your student account</h1><p>Your school record stays unchanged. Complete these steps once to enable portal access and password recovery.</p></header>
      <OnboardingProgress current={step}/>
      {step==='GOOGLE'?googlePanel():<form className="onboarding-stage" onSubmit={submit}><div><h2>Complete your student information</h2><p>Add your current academic, contact, and guardian details. Your Student Number and legal name remain controlled by the Discipline Office.</p></div><fieldset className="onboarding-fieldset"><legend>Academic information</legend><div className="onboarding-academic-fields"><div className="onboarding-academic-level"><span id="onboarding-academic-level-label">Academic level</span><div className="onboarding-academic-toggle" role="radiogroup" aria-labelledby="onboarding-academic-level-label">{[['COLLEGE','College'],['SENIOR_HIGH_SCHOOL','Senior High School']].map(([value,label])=><label key={value} className={form.academicLevel===value?'active':''}><input type="radio" name="academic_level" value={value} checked={form.academicLevel===value} onChange={changeAcademicLevel}/><span>{label}</span></label>)}</div></div><div className="onboarding-academic-grid">{form.academicLevel==='COLLEGE'&&<label className="onboarding-program-field">Program<ProgramSelect value={form.program} onChange={change('program')} required/></label>}<label>Section<input value={form.section} onChange={change('section')} maxLength="100" placeholder="Enter section" required/></label><label className="onboarding-year-field">Year level<select value={form.yearLevel} onChange={change('yearLevel')} required><option value="">Select year level</option>{yearLevelOptions.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label></div></div></fieldset><fieldset className="onboarding-fieldset"><legend>Contact and guardian information</legend><div className="student-form-grid"><PhoneInput id="onboarding-phone" name="phone_number" label="Student phone number" value={form.phoneNumber} onChange={change('phoneNumber')} required/><label>Guardian name<input value={form.guardianName} onChange={change('guardianName')} maxLength="200" required/></label><label>Guardian relationship<input value={form.guardianRelationship} onChange={change('guardianRelationship')} maxLength="100" required/></label><PhoneInput id="onboarding-guardian-phone" name="guardian_phone_number" label="Guardian phone number" value={form.guardianPhoneNumber} onChange={change('guardianPhoneNumber')} required/></div></fieldset><button disabled={busy}>{busy?'Saving student information…':'Save and enter portal'}</button></form>}
      {error&&<p className="error-message" id="onboarding-error" role="alert">{error}</p>}
      <button type="button" className="secondary-button onboarding-signout" onClick={onLogout} disabled={busy}>Sign out</button>
    </section>
  </main>
}
