import {useCallback,useEffect,useMemo,useRef,useState} from 'react'
import {API_URL} from '../lib/api.js'
import {formatManilaDateTime} from '../lib/displayFormat.js'
import PlatformMark from './PlatformMark.jsx'
import PortalIcon from './PortalIcon.jsx'

const readable=(value='')=>String(value).replaceAll('_',' ').toLowerCase().replace(/\b\w/g,(letter)=>letter.toUpperCase())
const json=async(response)=>{const data=await response.json().catch(()=>({}));if(!response.ok){const error=new Error(data.error?.message||data.message||'The request could not be completed.');error.code=data.error?.code||data.code;throw error}return data}
const componentFallbacks={api:{provider:'Render',technology:'Node.js / Express',icon:'render'},database:{provider:'Supabase',technology:'PostgreSQL',icon:'supabase'},google_identity:{provider:'Google',technology:'Google Identity Services',icon:'google'},email_delivery:{provider:'Brevo',technology:'HTTPS Email API',icon:'brevo'},realtime:{provider:'Socket.IO',technology:'WebSocket / polling',icon:'socketio'}}
const restrictionMessages={SELF_ACCOUNT_CHANGE:'You cannot lock the account you are currently using.',SELF_RECOVERY_NOT_ALLOWED:'Use Account Settings or the verified self-service flow to recover your own account.',ACCOUNT_ALREADY_LOCKED:'This account is already locked. Use recovery to restore access.',LAST_ADMIN:'The last active Discipline Administrator must remain available.',TARGET_CHANGED:'This account changed after password confirmation. Review it and try again.',STEP_UP_INVALID:'Password confirmation expired or was already used. Enter your password again.',STEP_UP_REQUIRED:'Enter your current administrator password to continue.',INVALID_CREDENTIALS:'The current password for the signed-in administrator is incorrect.',ACCOUNT_NOT_FOUND:'This account is no longer available. Refresh the search results.'}
const accountName=(account)=>[account?.first_name,account?.last_name].filter(Boolean).join(' ')||account?.username||'Unknown account'
const monitoringPanels=[
 {id:'overview',label:'Overview & Health'},
 {id:'security',label:'Security Events'},
 {id:'authentication',label:'Authentication Activity'},
 {id:'accounts',label:'Account Controls'},
]
const panelIds=new Set(monitoringPanels.map(({id})=>id))
const panelFromLocation=()=>{const requested=new URLSearchParams(window.location.search).get('panel');return panelIds.has(requested)?requested:'overview'}

export default function SystemDashboard({token,user}){
 const [system,setSystem]=useState(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[events,setEvents]=useState([]),[authActivity,setAuthActivity]=useState([])
 const [eventSearch,setEventSearch]=useState(''),[eventResult,setEventResult]=useState(''),[accountSearch,setAccountSearch]=useState(''),[accounts,setAccounts]=useState([]),[accountsLoading,setAccountsLoading]=useState(false)
 const [actionType,setActionType]=useState('ACCOUNT_RECOVERY'),[action,setAction]=useState({target_id:'',reason:'',password:''}),[actionError,setActionError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[credential,setCredential]=useState(null)
 const [activePanel,setActivePanel]=useState(panelFromLocation),[slideDirection,setSlideDirection]=useState('forward')
 const panelHeadingRef=useRef(null),tabRefs=useRef([])

 const loadStatus=useCallback(async()=>{setLoading(true);setError('');try{const response=await fetch(`${API_URL}/api/system/status`,{headers:{Authorization:`Bearer ${token}`}});setSystem((await json(response)).system)}catch(e){setError(e.message)}finally{setLoading(false)}},[token])
 const loadEvents=useCallback(async(search='',result='')=>{const query=new URLSearchParams({limit:'50'});if(search)query.set('search',search);if(result)query.set('result',result);try{const headers={Authorization:`Bearer ${token}`};const [eventResponse,authResponse]=await Promise.all([fetch(`${API_URL}/api/system/security-events?${query}`,{headers}),fetch(`${API_URL}/api/system/authentication-activity?limit=20`,{headers})]);if(eventResponse.ok)setEvents((await eventResponse.json()).events||[]);if(authResponse.ok)setAuthActivity((await authResponse.json()).activity||[])}catch{setEvents([])}},[token])
 const loadAccounts=useCallback(async(search='',signal)=>{setAccountsLoading(true);try{const response=await fetch(`${API_URL}/api/system/accounts?search=${encodeURIComponent(search)}&limit=20`,{headers:{Authorization:`Bearer ${token}`},signal});const data=await json(response);setAccounts(data.accounts||[]);return data.accounts||[]}finally{setAccountsLoading(false)}},[token])
 useEffect(()=>{loadStatus();loadEvents()},[loadStatus,loadEvents])
 useEffect(()=>{const controller=new AbortController();const timer=window.setTimeout(()=>loadAccounts(accountSearch,controller.signal).catch((loadError)=>{if(loadError.name!=='AbortError')setActionError(loadError.message)}),250);return()=>{window.clearTimeout(timer);controller.abort()}},[accountSearch,loadAccounts])
 useEffect(()=>()=>setCredential(null),[])
 useEffect(()=>{const url=new URL(window.location.href);if(url.searchParams.get('panel')!==activePanel){url.searchParams.set('panel',activePanel);window.history.replaceState({},'',`${url.pathname}${url.search}${url.hash}`)}},[activePanel])
 useEffect(()=>{const handlePopState=()=>{const next=panelFromLocation();setSlideDirection(monitoringPanels.findIndex(({id})=>id===next)>=monitoringPanels.findIndex(({id})=>id===activePanel)?'forward':'backward');setActivePanel(next)};window.addEventListener('popstate',handlePopState);return()=>window.removeEventListener('popstate',handlePopState)},[activePanel])

 const selectedAccount=useMemo(()=>accounts.find((account)=>String(account.id)===String(action.target_id))||null,[accounts,action.target_id])
 const restrictionCode=selectedAccount?(actionType==='ACCOUNT_LOCK'?selectedAccount.lock_restriction_code:selectedAccount.recovery_restriction_code):null
 const actionAllowed=selectedAccount?(actionType==='ACCOUNT_LOCK'?selectedAccount.can_lock:selectedAccount.can_recover):false
 const formReady=actionAllowed&&action.password&&action.reason.trim().length>=10&&!busy
 const chooseAction=(next)=>{setActionType(next);setAction((current)=>({...current,password:''}));setActionError('');setNotice('');setCredential(null)}
 const chooseAccount=(account)=>{setAction((current)=>({...current,target_id:String(account.id),password:''}));setActionError('');setNotice('');setCredential(null)}
 const executeAction=async(event)=>{event.preventDefault();if(!formReady)return;setBusy(true);setActionError('');setNotice('');setCredential(null);try{let response=await fetch(`${API_URL}/api/high-risk-actions/step-up`,{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({password:action.password,action_type:actionType,target_type:'USER_ACCOUNT',target_id:action.target_id})});const step=(await json(response)).step_up;response=await fetch(`${API_URL}/api/high-risk-actions/execute`,{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({action_type:actionType,target_id:action.target_id,reason:action.reason,step_up_token:step.token})});const data=await json(response);if(data.result?.temporary_password)setCredential({username:data.result.account?.username||selectedAccount?.username,password:data.result.temporary_password});setNotice(actionType==='ACCOUNT_LOCK'?'Account locked and existing sessions invalidated.':'Account access restored. Share the one-time password securely.');setAction((current)=>({...current,reason:'',password:''}));const refreshed=await loadAccounts(accountSearch);const updated=refreshed.find((account)=>String(account.id)===String(action.target_id));if(updated)setAction((current)=>({...current,target_id:String(updated.id)}));await loadEvents()}catch(e){setAction((current)=>({...current,password:''}));setActionError(restrictionMessages[e.code]||e.message)}finally{setBusy(false)}}
 const copyCredential=async()=>{try{await navigator.clipboard.writeText(credential.password);setNotice('Temporary password copied.')}catch{setActionError('Copy failed. Select the temporary password and copy it manually.')}}
 const components=Object.entries(system?.components||{})
 const activePanelIndex=monitoringPanels.findIndex(({id})=>id===activePanel)
 const selectPanel=(nextPanel,{focusHeading=false}={})=>{if(!panelIds.has(nextPanel)||nextPanel===activePanel)return;const nextIndex=monitoringPanels.findIndex(({id})=>id===nextPanel);setSlideDirection(nextIndex>activePanelIndex?'forward':'backward');setActivePanel(nextPanel);const url=new URL(window.location.href);url.searchParams.set('panel',nextPanel);window.history.pushState({},'',`${url.pathname}${url.search}${url.hash}`);if(focusHeading)window.requestAnimationFrame(()=>panelHeadingRef.current?.focus())}
 const handleTabKeyDown=(event,index)=>{let nextIndex;if(event.key==='ArrowRight')nextIndex=(index+1)%monitoringPanels.length;else if(event.key==='ArrowLeft')nextIndex=(index-1+monitoringPanels.length)%monitoringPanels.length;else if(event.key==='Home')nextIndex=0;else if(event.key==='End')nextIndex=monitoringPanels.length-1;else return;event.preventDefault();tabRefs.current[nextIndex]?.focus();selectPanel(monitoringPanels[nextIndex].id)}

 return <section className="system-dashboard" aria-labelledby="system-dashboard-title">
  <header className="management-page-header system-monitoring-hero"><div><span className="page-breadcrumb">Administration / System monitoring</span><h2 id="system-dashboard-title">System monitoring</h2><p>Service health, security activity, and controlled account recovery in one operational view.</p></div><span className={`status-badge status-${String(system?.status||'').toLowerCase()}`}>{loading?'Checking…':readable(system?.status||'Unavailable')}</span></header>
  {error&&<p className="error-message" role="alert">{error}</p>}
  <nav className="monitoring-panel-tabs" role="tablist" aria-label="System monitoring sections">{monitoringPanels.map((panel,index)=><button type="button" role="tab" id={`monitoring-tab-${panel.id}`} aria-controls={`monitoring-panel-${panel.id}`} aria-selected={activePanel===panel.id} tabIndex={activePanel===panel.id?0:-1} ref={(node)=>{tabRefs.current[index]=node}} onClick={()=>selectPanel(panel.id)} onKeyDown={(event)=>handleTabKeyDown(event,index)} key={panel.id}><span>{index+1}</span><b>{panel.label}</b></button>)}</nav>
  <div className="monitoring-slide-workspace">
  <section className="monitoring-slide" role="tabpanel" id={`monitoring-panel-${activePanel}`} aria-labelledby={`monitoring-tab-${activePanel}`} data-panel={activePanel} data-direction={slideDirection}><div className="monitoring-slide-scroll">
  <h3 className="monitoring-slide-title" tabIndex="-1" ref={panelHeadingRef}>{monitoringPanels[activePanelIndex].label}</h3>
  <div className="stats-grid system-summary-grid"><article className="stat-card"><i><PortalIcon name="monitoring"/></i><div><span>Application</span><strong>{system?.application||'STI Vio-Log'}</strong><small>{system?.environment||'—'}</small></div></article><article className="stat-card"><i><PortalIcon name="reports"/></i><div><span>Release</span><strong>{system?.version||'Not published'}</strong><small>Sanitized deployment identifier</small></div></article><article className="stat-card"><i><PortalIcon name="clearance"/></i><div><span>Database</span><strong>{readable(system?.database||(loading?'CHECKING':'UNAVAILABLE'))}</strong><small>{system?.components?.database?.latency_ms!=null?`${system.components.database.latency_ms} ms response`:'Connectivity check'}</small></div></article></div>

  <section className="table-card component-health-section"><div className="table-header"><div><span className="section-kicker">Live dependencies</span><h3>Component health</h3><p>Provider-aware checks without credentials or raw configuration.</p></div><button type="button" className="secondary-button" disabled={loading} onClick={loadStatus}>{loading?'Checking…':'Refresh checks'}</button></div><div className="component-health-grid">{loading&&!components.length?Object.keys(componentFallbacks).map((name)=><article className="component-health-card is-loading" key={name} aria-hidden="true"><span/><div/><small/></article>):components.map(([name,item])=>{const platform={...componentFallbacks[name],...item};return <article className={`component-health-card component-health-card--${name}`} key={name}><div className="component-health-heading"><span className="component-platform-logo"><PlatformMark name={platform.icon} label={platform.provider}/></span><div><span>{readable(name)}</span><strong>{platform.provider}</strong><small>{platform.technology}</small></div><span className={`status-badge status-${String(item.status||'').toLowerCase()}`}>{readable(item.status)}</span></div>{item.latency_ms!=null&&<p><b>{item.latency_ms} ms</b> response time</p>}{item.remediation&&<p className="component-remediation">{item.remediation}</p>}</article>})}</div><p className="health-checked">Last checked {system?.checked_at?formatManilaDateTime(system.checked_at):'not yet'}</p></section>

  <section className="table-card"><div className="table-header"><div><h3>Security events</h3><p>Search the append-only administrative security record.</p></div><span>{events.length} shown</span></div><form className="operations-filter" role="search" onSubmit={(e)=>{e.preventDefault();loadEvents(eventSearch,eventResult)}}><label><span>Search events</span><input value={eventSearch} onChange={(e)=>setEventSearch(e.target.value)} placeholder="Action, actor, or target"/></label><label><span>Result</span><select value={eventResult} onChange={(e)=>setEventResult(e.target.value)}><option value="">All results</option><option>SUCCESS</option><option>FAILED</option><option>DENIED</option></select></label><button>Apply filters</button></form><div className="table-wrap"><table><thead><tr><th>Time</th><th>Actor</th><th>Action</th><th>Target</th><th>Result</th></tr></thead><tbody>{events.map((event)=><tr key={event.id}><td>{formatManilaDateTime(event.occurred_at)}</td><td>{event.actor_readable_name||'Unauthenticated'}<br/><small>{readable(event.actor_role||'Unknown')}</small></td><td>{readable(event.action)}</td><td>{event.target_label||event.target_type||'—'}</td><td><span className="status-badge">{event.result}</span></td></tr>)}{!events.length&&<tr><td colSpan="5"><p className="empty-state">No events match these filters.</p></td></tr>}</tbody></table></div></section>
  <section className="table-card"><div className="table-header"><div><h3>Authentication activity</h3><p>Recent administrator sign-in and password-security activity.</p></div><span>{authActivity.length} recent</span></div><div className="table-wrap"><table><thead><tr><th>Time</th><th>Account</th><th>Action</th><th>Result</th></tr></thead><tbody>{authActivity.map((event)=><tr key={event.id}><td>{formatManilaDateTime(event.occurred_at)}</td><td>{event.actor_readable_name||event.target_label||'Unknown account'}</td><td>{readable(event.action)}</td><td><span className="status-badge">{event.result}</span></td></tr>)}{!authActivity.length&&<tr><td colSpan="4"><p className="empty-state">No authentication activity recorded.</p></td></tr>}</tbody></table></div></section>

  <section className="table-card account-security-workspace"><div className="table-header"><div><span className="section-kicker">Controlled access</span><h3>Account recovery and lock</h3><p>Choose one action, review the target account, then confirm with your current administrator password.</p></div></div>
   <div className="account-action-tabs" role="tablist" aria-label="Account action"><button type="button" role="tab" aria-selected={actionType==='ACCOUNT_RECOVERY'} onClick={()=>chooseAction('ACCOUNT_RECOVERY')}><PortalIcon name="settings"/><span><strong>Account recovery</strong><small>Restore access and issue a one-time password</small></span></button><button type="button" role="tab" aria-selected={actionType==='ACCOUNT_LOCK'} onClick={()=>chooseAction('ACCOUNT_LOCK')}><PortalIcon name="clearance"/><span><strong>Lock account</strong><small>Disable access and invalidate active sessions</small></span></button></div>
   {actionError&&<p className="error-message" role="alert">{actionError}</p>}{notice&&<p className="success-message" role="status">{notice}</p>}
   {credential&&<aside className="temporary-credential" aria-label="One-time recovery credential"><div><span>One-time password for</span><strong>{credential.username}</strong><code>{credential.password}</code><small>This password is shown once and must be changed at the next login.</small></div><div><button type="button" onClick={copyCredential}>Copy password</button><button type="button" className="secondary-button" onClick={()=>setCredential(null)}>Dismiss</button></div></aside>}
   <div className="account-action-layout"><div className="account-directory-panel"><label className="account-directory-search"><span>Find an account</span><div><PortalIcon name="search"/><input type="search" name="system-account-search" autoComplete="off" value={accountSearch} onChange={(e)=>setAccountSearch(e.target.value)} placeholder="Search name or username"/></div></label><div className="account-action-results" role="list" aria-busy={accountsLoading}>{accountsLoading&&!accounts.length?<p className="message-state">Loading accounts…</p>:accounts.map((account)=>{const selected=String(account.id)===String(action.target_id);return <button type="button" role="listitem" className={selected?'selected':''} aria-pressed={selected} key={account.id} onClick={()=>chooseAccount(account)}><span className="account-result-avatar">{accountName(account).charAt(0)}</span><span><strong>{accountName(account)}</strong><small>@{account.username} · {readable(account.role)}</small></span><b className={account.is_active?'is-active':'is-locked'}>{account.is_active?'Active':'Locked'}</b></button>})}{!accountsLoading&&!accounts.length&&<p className="message-state">No accounts match this search.</p>}</div></div>
    <form className="account-action-form" onSubmit={executeAction}><div className="selected-account-summary">{selectedAccount?<><span className="account-result-avatar">{accountName(selectedAccount).charAt(0)}</span><div><span>Selected account</span><strong>{accountName(selectedAccount)}</strong><small>@{selectedAccount.username} · {readable(selectedAccount.role)} · {selectedAccount.is_active?'Active':'Locked'}</small></div></>:<div><span>Selected account</span><strong>Choose an account from the directory</strong><small>The selected account and action eligibility will appear here.</small></div>}</div>{restrictionCode&&<p className="account-action-restriction" role="note">{restrictionMessages[restrictionCode]||'This action is not available for the selected account.'}</p>}<label><span>Current administrator password</span><input type="password" name="administrator_step_up_password" autoComplete="off" value={action.password} onChange={(e)=>setAction({...action,password:e.target.value})} placeholder={`Password for ${user?.username||'your signed-in account'}`} disabled={!selectedAccount}/><small>Enter the password for the account you are currently signed in with.</small></label><label><span>{actionType==='ACCOUNT_LOCK'?'Lock reason':'Recovery reason'}</span><textarea minLength="10" maxLength="1000" value={action.reason} onChange={(e)=>setAction({...action,reason:e.target.value})} placeholder={actionType==='ACCOUNT_LOCK'?'Describe why this account must be locked.':'Describe the verified recovery request.'} disabled={!selectedAccount}/><small>{action.reason.trim().length} / 10 minimum</small></label><button type="submit" className={actionType==='ACCOUNT_LOCK'?'danger-button':'primary-action'} disabled={!formReady}>{busy?'Confirming…':actionType==='ACCOUNT_LOCK'?'Lock account':'Start recovery'}</button></form></div>
  </section>
  </div></section>
  </div>
 </section>
}
