const test=require('node:test');
const assert=require('node:assert/strict');
const {createAdminAccountService}=require('../src/services/adminAccountService');
const {createStudentPasswordAuthService}=require('../src/services/studentPasswordAuthService');

test('non-admin accounts cannot read administrator profile settings',async()=>{const pool={connect:async()=>({}),query:async()=>({rows:[]})};const service=createAdminAccountService({pool,otpService:{}});await assert.rejects(service.getProfile({userId:7}),error=>error.code==='ADMIN_REQUIRED')});

test('admin profile changes are transactional, audited, and trigger email verification',async()=>{const calls=[];const client={query:async(sql,params)=>{calls.push({sql:String(sql),params});if(String(sql).includes("u.role='ADMIN' FOR UPDATE"))return{rows:[{id:3,username:'old',email:'old@example.com'}]};if(String(sql).startsWith('SELECT 1 FROM'))return{rows:[]};return{rows:[]}},release(){}};let issued;const pool={connect:async()=>client,query:async()=>({rows:[{id:3,username:'main.admin',role:'ADMIN',first_name:'Main',last_name:'Officer',email:'main@example.com',email_verified:false}]})};const service=createAdminAccountService({pool,otpService:{issue:async(input)=>{issued=input}}});const result=await service.updateProfile({userId:3,firstName:' Main ',lastName:' Officer ',username:' Main.Admin ',email:' MAIN@example.com'});assert.equal(result.verification_required,true);assert.equal(issued.purpose,'ADMIN_EMAIL_VERIFICATION');assert(calls.some(call=>call.params?.includes('ADMIN_EMAIL_CHANGE')));assert(calls.some(call=>call.sql==='COMMIT'));assert.equal(JSON.stringify(calls).includes('password'),false)});

test('duplicate administrator email is rejected without issuing a code',async()=>{const client={query:async(sql)=>{if(String(sql).includes("u.role='ADMIN' FOR UPDATE"))return{rows:[{id:3,email:null}]};if(String(sql).startsWith('SELECT 1 FROM'))return{rows:[{exists:true}]};return{rows:[]}},release(){}};let issued=false;const service=createAdminAccountService({pool:{connect:async()=>client,query:async()=>({rows:[]})},otpService:{issue:async()=>{issued=true}}});await assert.rejects(service.updateProfile({userId:3,firstName:'Main',lastName:'Officer',username:'admin',email:'used@example.com'}),error=>error.code==='ACCOUNT_CONFLICT');assert.equal(issued,false)});

test('verified administrator email participates in the generic non-disclosing recovery flow',async()=>{let issued;const pool={connect:async()=>({}),query:async(sql)=>{assert.match(String(sql),/ap\.email_verified=TRUE/);return{rows:[{id:3,email:'main@example.com',purpose:'ADMIN_PASSWORD_RESET'}]}}};const service=createStudentPasswordAuthService({pool,otpService:{issue:async(input)=>{issued=input}},hashPassword:async()=>'',comparePassword:async()=>false});await service.requestPasswordReset({identifier:'main@example.com'});assert.equal(issued.purpose,'ADMIN_PASSWORD_RESET');assert.equal(issued.userId,3)});
