const test = require('node:test');
const assert = require('node:assert/strict');
const router = require('../src/routes/duplicateAccountReviewRoutes');
const { createDuplicateAccountReviewController } = require('../src/controllers/duplicateAccountReviewController');
const { createDuplicateAccountReviewService, groupCandidates } = require('../src/services/duplicateAccountReviewService');
const response = () => ({ statusCode: 200, body: null, status(code) { this.statusCode = code; return this; }, json(body) { this.body = body; return this; } });

test('duplicate review exposes a single read-only route',()=>{const routes=router.stack.filter(layer=>layer.route).map(layer=>`${Object.keys(layer.route.methods)[0].toUpperCase()} ${layer.route.path}`);assert.deepEqual(routes,['GET /'])});
test('Google grouping never returns its internal subject',()=>{const conflicts=groupCandidates([{match_key:'private-google-sub',source:'GOOGLE_LINK',record_id:1},{match_key:'private-google-sub',source:'STUDENT_REGISTRATION',record_id:2}],'GOOGLE_IDENTITY',{hidden:true});assert.equal(conflicts[0].identifier,'Hidden Google identity');assert.equal(JSON.stringify(conflicts).includes('private-google-sub'),false)});
test('review service reports cross-source conflicts and omits passwords, emails, and tokens',async()=>{const pool={async query(sql){if(sql.includes("'STUDENT' source"))return{rows:[{match_key:'02000123456',source:'STUDENT',record_id:1,display:'02000123456'},{match_key:'02000123456',source:'STUDENT_REGISTRATION',record_id:2,display:'02000123456'}]};if(sql.includes("'STAFF' source"))return{rows:[]};if(sql.includes("'USER' source"))return{rows:[]};return{rows:[{match_key:'google-private',source:'GOOGLE_LINK',record_id:4,display:'Linked account'},{match_key:'google-private',source:'DEPARTMENT_REGISTRATION',record_id:5,display:'Pending department request'}]}}};const result=await createDuplicateAccountReviewService({pool}).list();assert.equal(result.summary.total,2);const serialized=JSON.stringify(result);assert.equal(serialized.includes('google-private'),false);for(const forbidden of ['password_hash','google_email','token','credential'])assert.equal(serialized.includes(forbidden),false)});
test('controller rejects all query overrides',async()=>{let called=false;const controller=createDuplicateAccountReviewController({service:{async list(){called=true}}});const res=response();await controller.list({query:{google_subject:'private'}},res);assert.equal(res.statusCode,400);assert.equal(called,false)});
