const test = require('node:test');
const assert = require('node:assert/strict');
const router = require('../src/routes/googleLinkAdministrationRoutes');
const { createGoogleLinkAdministrationController } = require('../src/controllers/googleLinkAdministrationController');
const { createGoogleLinkAdministrationService, RECOVERY_FAILURE } = require('../src/services/googleLinkAdministrationService');
const response = () => ({ statusCode: 200, body: null, status(code) { this.statusCode = code; return this; }, json(body) { this.body = body; return this; } });
const fakePool = (link) => { const queries = []; const client = { async query(sql, params) { queries.push({ sql, params }); if (sql.includes('SELECT gil.id')) return { rows: link ? [link] : [] }; return { rows: [] }; }, release() {} }; return { queries, pool: { async connect() { return client; } } }; };

test('Google recovery route exposes only explicit revocation', () => { const routes = router.stack.filter((layer) => layer.route).map((layer) => `${Object.keys(layer.route.methods)[0].toUpperCase()} ${layer.route.path}`); assert.deepEqual(routes, ['POST /:studentId/google-link/revoke']); });
test('controller derives the administrator and rejects identity overrides', async () => { let called = false; const controller = createGoogleLinkAdministrationController({ service: { async revokeStudentLink() { called = true; } } }); const res = response(); await controller.revoke({ user: { id: 4 }, params: { studentId: '8' }, body: { reason: 'verified', google_subject: 'private' } }, res); assert.equal(res.statusCode, 400); assert.equal(called, false); });
test('recovery revokes history, invalidates sessions, and records no Google claims', async () => { const fake = fakePool({ link_id: 91, user_id: 12 }); const service = createGoogleLinkAdministrationService({ pool: fake.pool }); assert.deepEqual(await service.revokeStudentLink({ actorId: 4, studentId: 8, reason: 'Identity confirmed' }), { student_id: 8, revoked: true }); const sql = fake.queries.map((query) => query.sql).join('\n'); assert.match(sql, /revoked_at = CURRENT_TIMESTAMP/); assert.match(sql, /session_version = session_version \+ 1/); assert.match(sql, /GOOGLE_LINK_REVOKE/); assert.doesNotMatch(sql, /google_email\s*=/); });
test('missing and already-revoked links return the same non-sensitive conflict', async () => { const service = createGoogleLinkAdministrationService({ pool: fakePool(null).pool }); await assert.rejects(service.revokeStudentLink({ actorId: 4, studentId: 8, reason: 'Identity confirmed' }), (error) => error.statusCode === 409 && error.message === RECOVERY_FAILURE); });
