const test = require('node:test');
const assert = require('node:assert/strict');
const path = require('node:path');
const { runProductionCheck } = require('../scripts/production-check');
const { listMigrationFiles } = require('../scripts/migrate');

const environment={NODE_ENV:'production',DEPLOYMENT_ENV:'production',DATABASE_ENVIRONMENT:'production',TRUST_PROXY_HOPS:'1',JWT_SECRET:'s'.repeat(48),SESSION_HASH_KEY:'a'.repeat(48),CSRF_SIGNING_KEY:'b'.repeat(48),OTP_HASH_KEY:'c'.repeat(48),AUTH_THROTTLE_KEY:'d'.repeat(48),MFA_RECOVERY_KEY:'e'.repeat(48),MFA_ENCRYPTION_KEY:Buffer.alloc(32,9).toString('base64'),CERTIFICATE_SIGNING_KEY:'f'.repeat(48),DATABASE_URL:'postgresql://example',DB_SSL:'require',FRONTEND_URL:'https://portal.example.test'};
const currentMigrations=listMigrationFiles(path.resolve(__dirname,'../../database/migrations'));
test('production check confirms a least-privilege runtime role, connectivity, current migrations, and database security without returning secrets',async()=>{const queries=[];const database={async query(sql){queries.push(sql);if(sql.includes('SELECT 1 AS healthy'))return{rows:[{healthy:1}]};if(sql.includes('current_schema()'))return{rows:[{name:'public'}]};if(sql.includes('pg_has_role'))return{rows:[{runtime_member:true,rolsuper:false,rolcreatedb:false,rolcreaterole:false,rolbypassrls:false,owns_app_tables:false}]};if(sql.includes('SELECT migration_name'))return{rows:currentMigrations.map(migration_name=>({migration_name}))};if(sql.includes('FROM pg_tables WHERE'))return{rows:[{total:40,rls:40}]};if(sql.includes('role_table_grants')||sql.includes('routine_privileges')||sql.includes('pg_proc'))return{rows:[{count:0}]};return{rows:[]}}};const result=await runProductionCheck({environment,database});assert.equal(result.database,'connected');assert.equal(result.migrations,'current');assert.equal(result.database_security,'passed');assert.equal(JSON.stringify(result).includes(environment.JWT_SECRET),false);assert.equal(queries.some(sql=>/^\s*(CREATE|ALTER|INSERT|UPDATE|DELETE|DROP)\b/i.test(sql)),false)});
test('production check refuses development configuration',async()=>{await assert.rejects(runProductionCheck({environment:{...environment,NODE_ENV:'development'},database:{query(){throw new Error('must not connect')}}}),/NODE_ENV/)});
