const test = require('node:test');
const assert = require('node:assert/strict');
const { allowedOriginsFor, CORS_METHODS, validateSecureConfig } = require('../src/config/security');

const secure = { NODE_ENV:'production',JWT_SECRET:'a'.repeat(48),SESSION_HASH_KEY:'b'.repeat(48),CSRF_SIGNING_KEY:'c'.repeat(48),OTP_HASH_KEY:'d'.repeat(48),AUTH_THROTTLE_KEY:'e'.repeat(48),MFA_RECOVERY_KEY:'f'.repeat(48),MFA_ENCRYPTION_KEY:Buffer.alloc(32,7).toString('base64'),CERTIFICATE_SIGNING_KEY:'g'.repeat(48),DATABASE_URL:'postgresql://example',DB_SSL:'require',FRONTEND_URL:'https://portal.example.test',GOOGLE_CLIENT_ID:'123.apps.googleusercontent.com' };
test('production accepts DATABASE_URL without redundant DB parts',()=>{assert.doesNotThrow(()=>validateSecureConfig(secure))});
test('production rejects localhost, HTTP, missing origins, insecure TLS, reused keys, and placeholders',()=>{assert.throws(()=>validateSecureConfig({...secure,FRONTEND_URL:'http://localhost:5173'}),/HTTPS/);assert.throws(()=>validateSecureConfig({...secure,FRONTEND_URL:''}),/required/);assert.throws(()=>validateSecureConfig({...secure,JWT_SECRET:'change-this-to-a-long-random-secret'}),/JWT_SECRET/);assert.throws(()=>validateSecureConfig({...secure,SESSION_HASH_KEY:'replace-with-an-independent-random-secret-at-least-32-characters'}),/SESSION_HASH_KEY/);assert.throws(()=>validateSecureConfig({...secure,DB_SSL:'disable'}),/verified TLS/);assert.throws(()=>validateSecureConfig({...secure,CSRF_SIGNING_KEY:secure.SESSION_HASH_KEY}),/independent/)});
test('production CORS excludes local origins while development includes them',()=>{assert.deepEqual(allowedOriginsFor(secure),['https://portal.example.test']);assert.ok(allowedOriginsFor({...secure,NODE_ENV:'development'}).includes('http://localhost:5173'))});
test('CORS supports every application mutation method including PATCH',()=>{assert.ok(CORS_METHODS.includes('PATCH'));assert.ok(CORS_METHODS.includes('POST'));assert.ok(CORS_METHODS.includes('DELETE'))});
