const test=require('node:test');
const assert=require('node:assert/strict');
const pool=require('../src/config/database');
const {createStudent,updateStudent,resetStudentPassword}=require('../src/controllers/studentController');
const response=()=>({statusCode:200,body:null,status(code){this.statusCode=code;return this},json(body){this.body=body;return this}});

test('student creation rejects legacy user_id ownership input',async()=>{const res=response();await createStudent({user:{id:1},body:{user_id:9,student_number:'02000123456',first_name:'Test',last_name:'Student',qr_code:'opaque'}},res);assert.equal(res.statusCode,400)});

test('student number creates the local student account and profile atomically',async()=>{const originalConnect=pool.connect;const queries=[];pool.connect=async()=>({query:async(sql,params)=>{const text=String(sql);queries.push({text,params});if(text.includes('INSERT INTO users'))return{rows:[{id:44}]};if(text.includes('INSERT INTO students'))return{rows:[{id:55,user_id:44,student_number:params[1],first_name:params[2],last_name:params[4]}]};return{rows:[]}},release(){}});try{const res=response();await createStudent({user:{id:1},ip:'127.0.0.1',body:{student_number:'02000123456',first_name:'Test',last_name:'Student',section:'A103',qr_code:'opaque-qr'}},res);assert.equal(res.statusCode,201);assert.equal(res.body.student.user_id,44);assert(queries.some(({text,params})=>text.includes('INSERT INTO users')&&params[0]==='02000123456'));assert.equal(JSON.stringify(res.body).includes('password'),false);assert(queries.some(({text})=>text.includes("'STUDENT_CREATE'")))}finally{pool.connect=originalConnect}});

test('student information update keeps the local username synchronized and audits the reason',async()=>{const originalConnect=pool.connect;const queries=[];pool.connect=async()=>({query:async(sql,params)=>{const text=String(sql);queries.push({text,params});if(text.includes('SELECT id,user_id,student_number'))return{rows:[{id:55,user_id:44,student_number:'OLD-1'}]};if(text.includes('UPDATE students'))return{rows:[{id:55,student_number:'NEW-2',first_name:'Updated',last_name:'Student'}]};return{rows:[]}},release(){}});try{const res=response();await updateStudent({user:{id:1},params:{id:'55'},ip:'127.0.0.1',body:{student_number:'NEW-2',first_name:'Updated',last_name:'Student',reason:'Corrected school record'}},res);assert.equal(res.statusCode,200);assert(queries.some(({text,params})=>text.includes('UPDATE users SET username')&&params[1]==='new-2'));assert(queries.some(({text,params})=>text.includes("'STUDENT_UPDATE'")&&params[2].includes('Corrected school record')))}finally{pool.connect=originalConnect}});

test('student password reset returns a one-time credential and forces password change',async()=>{const originalConnect=pool.connect;const queries=[];pool.connect=async()=>({query:async(sql,params)=>{const text=String(sql);queries.push({text,params});if(text.includes("u.role='STUDENT'"))return{rows:[{id:44,username:'new-2'}]};return{rows:[]}},release(){}});try{const res=response();await resetStudentPassword({user:{id:1},params:{id:'55'},ip:'127.0.0.1',body:{reason:'Student requested local access'}},res);assert.equal(res.statusCode,200);assert.equal(res.body.account.username,'new-2');assert.match(res.body.temporary_password,/!Aa1$/);assert(queries.some(({text})=>text.includes('must_change_password=TRUE')&&text.includes('session_version=session_version+1')));assert(queries.some(({text})=>text.includes("'STUDENT_PASSWORD_RESET'")))}finally{pool.connect=originalConnect}});
