const bcrypt=require('bcrypt');
const crypto=require('node:crypto');
const {ApiError}=require('../utils/api');
const {isPositiveId}=require('../utils/validators');

const ROLES=new Set(['ADMIN','DISCIPLINE_OFFICE','DEPARTMENT_HEAD']);
const clean=(value,max=100)=>typeof value==='string'?value.normalize('NFKC').trim().replace(/\s+/g,' ').slice(0,max):'';
const publicAccount=(row)=>({id:Number(row.id),username:row.username,role:row.role,is_active:Boolean(row.is_active),must_change_password:Boolean(row.must_change_password),session_version:Number(row.session_version),first_name:row.first_name,last_name:row.last_name,employee_number:row.employee_number||null,email:row.email||null,department_id:row.department_id?Number(row.department_id):null,department_name:row.department_name||null,created_at:row.created_at});

const createAccountAdministrationService=({pool,hashPassword=(value)=>bcrypt.hash(value,12),randomBytes=crypto.randomBytes}={})=>{
  if(!pool?.connect)throw new TypeError('Account administration dependencies are required');
  const list=async({page=1,limit=25,role,status,search}={})=>{
    const p=Number(page),l=Number(limit);if(!Number.isInteger(p)||p<1||!Number.isInteger(l)||l<1||l>100)throw new ApiError(400,'VALIDATION_ERROR','Invalid pagination');
    const params=[];const where=["u.role <> 'STUDENT'"];
    if(role){const r=String(role).toUpperCase();if(!ROLES.has(r))throw new ApiError(400,'VALIDATION_ERROR','Invalid staff role');params.push(r);where.push(`u.role=$${params.length}`)}
    if(status){if(!['active','inactive'].includes(String(status).toLowerCase()))throw new ApiError(400,'VALIDATION_ERROR','status must be active or inactive');params.push(String(status).toLowerCase()==='active');where.push(`u.is_active=$${params.length}`)}
    if(search){params.push(`%${clean(search,100).toLowerCase()}%`);where.push(`(LOWER(u.username) LIKE $${params.length} OR LOWER(COALESCE(sp.first_name,dh.first_name,'')) LIKE $${params.length} OR LOWER(COALESCE(sp.last_name,dh.last_name,'')) LIKE $${params.length})`)}
    const count=await pool.query(`SELECT COUNT(*)::int count FROM users u LEFT JOIN staff_profiles sp ON sp.user_id=u.id LEFT JOIN department_heads dh ON dh.user_id=u.id WHERE ${where.join(' AND ')}`,params);
    params.push(l,(p-1)*l);const rows=await pool.query(`SELECT u.id,u.username,u.role,u.is_active,u.must_change_password,u.session_version,u.created_at,COALESCE(sp.first_name,dh.first_name) first_name,COALESCE(sp.last_name,dh.last_name) last_name,COALESCE(sp.employee_number,dh.employee_number) employee_number,COALESCE(sp.email,dh.email) email,dh.department_id,d.department_name FROM users u LEFT JOIN staff_profiles sp ON sp.user_id=u.id LEFT JOIN department_heads dh ON dh.user_id=u.id LEFT JOIN departments d ON d.id=dh.department_id WHERE ${where.join(' AND ')} ORDER BY u.created_at DESC,u.id DESC LIMIT $${params.length-1} OFFSET $${params.length}`,params);
    return{accounts:rows.rows.map(publicAccount),pagination:{page:p,limit:l,total:Number(count.rows[0].count)}};
  };

  const create=async({actorId,username,role,firstName,lastName,employeeNumber,email,departmentId,enforceSingleDepartmentAccount=false})=>{
    const values={username:clean(username,100).toLowerCase(),role:String(role||'').toUpperCase(),firstName:clean(firstName),lastName:clean(lastName),employeeNumber:clean(employeeNumber,50)||null,email:clean(email,255).toLowerCase()||null};
    if(!isPositiveId(actorId)||!values.username||!ROLES.has(values.role)||!values.firstName||!values.lastName||(values.role==='DEPARTMENT_HEAD'&&!isPositiveId(departmentId))||(values.role!=='DEPARTMENT_HEAD'&&departmentId!=null))throw new ApiError(400,'VALIDATION_ERROR','Valid staff identity, role, and department assignment are required');
    const client=await pool.connect();try{await client.query('BEGIN');if(values.role==='DEPARTMENT_HEAD'){if(enforceSingleDepartmentAccount){await client.query("SELECT pg_advisory_xact_lock(hashtext('department-account:' || $1::text))",[Number(departmentId)]);const existing=(await client.query("SELECT 1 FROM users u JOIN department_heads dh ON dh.user_id=u.id WHERE dh.department_id=$1 AND u.role='DEPARTMENT_HEAD' AND u.is_active=TRUE",[Number(departmentId)])).rows[0];if(existing)throw new ApiError(409,'DEPARTMENT_ACCOUNT_EXISTS','This department already has an active Department Account')}const d=(await client.query('SELECT id FROM departments WHERE id=$1 AND is_active=TRUE FOR UPDATE',[Number(departmentId)])).rows[0];if(!d)throw new ApiError(400,'VALIDATION_ERROR','Select an active department')}
      const temporaryPassword=randomBytes(18).toString('base64url')+'!Aa1';const hash=await hashPassword(temporaryPassword);const user=(await client.query(`INSERT INTO users(username,password_hash,role,is_active,must_change_password)VALUES($1,$2,$3,TRUE,TRUE)RETURNING id,username,role,is_active,must_change_password,session_version,created_at`,[values.username,hash,values.role])).rows[0];
      if(values.role==='DEPARTMENT_HEAD')await client.query(`INSERT INTO department_heads(user_id,department_id,employee_number,first_name,last_name,email,qr_scanner_enabled)VALUES($1,$2,$3,$4,$5,$6,TRUE)`,[user.id,Number(departmentId),values.employeeNumber,values.firstName,values.lastName,values.email]);else await client.query(`INSERT INTO staff_profiles(user_id,employee_number,first_name,last_name,email)VALUES($1,$2,$3,$4,$5)`,[user.id,values.employeeNumber,values.firstName,values.lastName,values.email]);
      await client.query(`INSERT INTO audit_logs(user_id,action,table_name,record_id,description)VALUES($1,'ACCOUNT_CREATE','users',$2,$3)`,[Number(actorId),user.id,`Created individual ${values.role} account`]);await client.query('COMMIT');return{account:publicAccount({...user,first_name:values.firstName,last_name:values.lastName,employee_number:values.employeeNumber,email:values.email,department_id:values.role==='DEPARTMENT_HEAD'?Number(departmentId):null}),temporary_password:temporaryPassword};
    }catch(error){try{await client.query('ROLLBACK')}catch(_){}if(error.code==='23505')throw new ApiError(409,'ACCOUNT_CONFLICT','Unable to create this account');throw error}finally{client.release()}
  };

  const setStatus=async({actorId,targetId,isActive,reason})=>{const why=clean(reason,1000);if(!isPositiveId(actorId)||!isPositiveId(targetId)||typeof isActive!=='boolean'||!why)throw new ApiError(400,'VALIDATION_ERROR','Status and reason are required');if(Number(actorId)===Number(targetId))throw new ApiError(409,'SELF_ACCOUNT_CHANGE','You cannot change your own account status');const client=await pool.connect();try{await client.query('BEGIN');await client.query("SELECT pg_advisory_xact_lock(hashtext('active-admin-guard'))");const target=(await client.query('SELECT id,role,is_active FROM users WHERE id=$1 FOR UPDATE',[Number(targetId)])).rows[0];if(!target||target.role==='STUDENT')throw new ApiError(404,'ACCOUNT_NOT_FOUND','Staff account not found');if(target.is_active===isActive)throw new ApiError(409,'ACCOUNT_STATE_UNCHANGED','Account already has that status');if(!isActive&&target.role==='ADMIN'){const count=await client.query("SELECT COUNT(*)::int count FROM users WHERE role='ADMIN' AND is_active=TRUE");if(Number(count.rows[0].count)<=1)throw new ApiError(409,'LAST_ADMIN','The last active administrator cannot be deactivated')}
      if(isActive&&target.role==='DEPARTMENT_HEAD'){const mapping=(await client.query('SELECT 1 FROM department_heads dh JOIN departments d ON d.id=dh.department_id WHERE dh.user_id=$1 AND d.is_active=TRUE',[target.id])).rows[0];if(!mapping)throw new ApiError(409,'DEPARTMENT_REQUIRED','An active department assignment is required')}
      const row=(await client.query(`UPDATE users SET is_active=$2::boolean,deactivated_at=CASE WHEN $2::boolean THEN NULL::timestamptz ELSE CURRENT_TIMESTAMP END,deactivated_by=CASE WHEN $2::boolean THEN NULL::bigint ELSE $3::bigint END,session_version=session_version+1,updated_at=CURRENT_TIMESTAMP WHERE id=$1 RETURNING id,username,role,is_active,must_change_password,session_version,created_at`,[target.id,isActive,Number(actorId)])).rows[0];await client.query(`INSERT INTO audit_logs(user_id,action,table_name,record_id,description)VALUES($1,$2,'users',$3,$4)`,[Number(actorId),isActive?'ACCOUNT_ACTIVATE':'ACCOUNT_DEACTIVATE',target.id,`${isActive?'Activated':'Deactivated'} staff account: ${why}`]);await client.query('COMMIT');return publicAccount(row);
    }catch(error){try{await client.query('ROLLBACK')}catch(_){}throw error}finally{client.release()}};

  const resetPassword=async({actorId,targetId,reason})=>{const why=clean(reason,1000);if(!isPositiveId(actorId)||!isPositiveId(targetId)||!why)throw new ApiError(400,'VALIDATION_ERROR','A reset reason is required');const client=await pool.connect();try{await client.query('BEGIN');const target=(await client.query("SELECT id,role FROM users WHERE id=$1 AND role<>'STUDENT' FOR UPDATE",[Number(targetId)])).rows[0];if(!target)throw new ApiError(404,'ACCOUNT_NOT_FOUND','Staff account not found');const temporaryPassword=randomBytes(18).toString('base64url')+'!Aa1';const hash=await hashPassword(temporaryPassword);await client.query('UPDATE users SET password_hash=$2,must_change_password=TRUE,session_version=session_version+1,updated_at=CURRENT_TIMESTAMP WHERE id=$1',[target.id,hash]);await client.query(`INSERT INTO audit_logs(user_id,action,table_name,record_id,description)VALUES($1,'ACCOUNT_PASSWORD_RESET','users',$2,$3)`,[Number(actorId),target.id,`Reset staff account password: ${why}`]);await client.query('COMMIT');return{account_id:Number(target.id),temporary_password:temporaryPassword};}catch(error){try{await client.query('ROLLBACK')}catch(_){}throw error}finally{client.release()}};
  const assign=async({actorId,targetId,role,departmentId,reason})=>{const nextRole=String(role||'').toUpperCase(),why=clean(reason,1000);if(!isPositiveId(actorId)||!isPositiveId(targetId)||!ROLES.has(nextRole)||!why||(nextRole==='DEPARTMENT_HEAD'&&!isPositiveId(departmentId))||(nextRole!=='DEPARTMENT_HEAD'&&departmentId!=null))throw new ApiError(400,'VALIDATION_ERROR','Valid role, department assignment, and reason are required');if(Number(actorId)===Number(targetId))throw new ApiError(409,'SELF_ACCOUNT_CHANGE','You cannot change your own role or assignment');const client=await pool.connect();try{await client.query('BEGIN');await client.query("SELECT pg_advisory_xact_lock(hashtext('active-admin-guard'))");const target=(await client.query(`SELECT u.id,u.role,u.is_active,COALESCE(sp.first_name,dh.first_name) first_name,COALESCE(sp.last_name,dh.last_name) last_name,COALESCE(sp.employee_number,dh.employee_number) employee_number,COALESCE(sp.email,dh.email) email,dh.department_id FROM users u LEFT JOIN staff_profiles sp ON sp.user_id=u.id LEFT JOIN department_heads dh ON dh.user_id=u.id WHERE u.id=$1 FOR UPDATE OF u`,[Number(targetId)])).rows[0];if(!target||target.role==='STUDENT')throw new ApiError(404,'ACCOUNT_NOT_FOUND','Staff account not found');if(target.role==='ADMIN'&&nextRole!=='ADMIN'&&target.is_active){const count=await client.query("SELECT COUNT(*)::int count FROM users WHERE role='ADMIN' AND is_active=TRUE");if(Number(count.rows[0].count)<=1)throw new ApiError(409,'LAST_ADMIN','The last active administrator cannot be reassigned')}
      if(nextRole==='DEPARTMENT_HEAD'){const department=(await client.query('SELECT id FROM departments WHERE id=$1 AND is_active=TRUE FOR UPDATE',[Number(departmentId)])).rows[0];if(!department)throw new ApiError(400,'VALIDATION_ERROR','Select an active department')}
      if(target.role==='DEPARTMENT_HEAD'&&nextRole!=='DEPARTMENT_HEAD'){await client.query('DELETE FROM department_heads WHERE user_id=$1',[target.id]);await client.query(`INSERT INTO staff_profiles(user_id,employee_number,first_name,last_name,email)VALUES($1,$2,$3,$4,$5)`,[target.id,target.employee_number,target.first_name,target.last_name,target.email])}
      else if(target.role!=='DEPARTMENT_HEAD'&&nextRole==='DEPARTMENT_HEAD'){await client.query('DELETE FROM staff_profiles WHERE user_id=$1',[target.id]);await client.query(`INSERT INTO department_heads(user_id,department_id,employee_number,first_name,last_name,email,qr_scanner_enabled)VALUES($1,$2,$3,$4,$5,$6,TRUE)`,[target.id,Number(departmentId),target.employee_number,target.first_name,target.last_name,target.email])}
      else if(nextRole==='DEPARTMENT_HEAD'&&Number(target.department_id)!==Number(departmentId))await client.query('UPDATE department_heads SET department_id=$2 WHERE user_id=$1',[target.id,Number(departmentId)]);
      await client.query('UPDATE users SET role=$2,session_version=session_version+1,updated_at=CURRENT_TIMESTAMP WHERE id=$1',[target.id,nextRole]);await client.query(`INSERT INTO audit_logs(user_id,action,table_name,record_id,description)VALUES($1,'ACCOUNT_ROLE_CHANGE','users',$2,$3)`,[Number(actorId),target.id,`Changed staff role from ${target.role} to ${nextRole}: ${why}`]);await client.query('COMMIT');return{account_id:Number(target.id),role:nextRole,department_id:nextRole==='DEPARTMENT_HEAD'?Number(departmentId):null};
    }catch(error){try{await client.query('ROLLBACK')}catch(_){}if(error.code==='23505')throw new ApiError(409,'ACCOUNT_CONFLICT','Unable to change this account assignment');throw error}finally{client.release()}};
  return{list,create,setStatus,assign,resetPassword};
};
module.exports={createAccountAdministrationService,publicAccount,ROLES};
