const {ApiError}=require('../utils/api');
const {isPositiveId}=require('../utils/validators');
const clean=(value,max)=>typeof value==='string'?value.normalize('NFKC').trim().replace(/\s+/g,' ').slice(0,max):'';
const publicDepartment=(row)=>({id:Number(row.id),department_code:row.department_code,department_name:row.department_name,description:row.description||null,is_active:Boolean(row.is_active),assigned_accounts:Number(row.assigned_accounts||0),active_accounts:Number(row.active_accounts||0),created_at:row.created_at});

const createDepartmentAdministrationService=({pool}={})=>{
 if(!pool?.connect)throw new TypeError('Department administration dependencies are required');
 const list=async()=>{const result=await pool.query(`SELECT d.id,d.department_code,d.department_name,d.description,d.is_active,d.created_at,COUNT(dh.id)::int assigned_accounts,COUNT(dh.id) FILTER (WHERE u.is_active=TRUE)::int active_accounts FROM departments d LEFT JOIN department_heads dh ON dh.department_id=d.id LEFT JOIN users u ON u.id=dh.user_id GROUP BY d.id ORDER BY d.department_name,d.id`);return result.rows.map(publicDepartment)};
 const create=async({actorId,code,name,description})=>{const values={code:clean(code,50).toUpperCase(),name:clean(name,150),description:clean(description,1000)||null};if(!isPositiveId(actorId)||!values.code||!values.name)throw new ApiError(400,'VALIDATION_ERROR','Department code and official name are required');const client=await pool.connect();try{await client.query('BEGIN');const row=(await client.query(`INSERT INTO departments(department_code,department_name,description,is_active)VALUES($1,$2,$3,TRUE)RETURNING *`,[values.code,values.name,values.description])).rows[0];await client.query(`INSERT INTO audit_logs(user_id,action,table_name,record_id,description)VALUES($1,'DEPARTMENT_CREATE','departments',$2,$3)`,[Number(actorId),row.id,'Created department configuration']);await client.query('COMMIT');return publicDepartment(row)}catch(error){try{await client.query('ROLLBACK')}catch(_){}if(error.code==='23505')throw new ApiError(409,'DEPARTMENT_CONFLICT','A department with that code already exists');throw error}finally{client.release()}};
 const update=async({actorId,departmentId,code,name,description,isActive,reason})=>{const why=clean(reason,1000);if(!isPositiveId(actorId)||!isPositiveId(departmentId)||!why||![code,name,description,isActive].some(v=>v!==undefined))throw new ApiError(400,'VALIDATION_ERROR','At least one department change and a reason are required');if(isActive!==undefined&&typeof isActive!=='boolean')throw new ApiError(400,'VALIDATION_ERROR','is_active must be boolean');const client=await pool.connect();try{await client.query('BEGIN');const current=(await client.query('SELECT * FROM departments WHERE id=$1 FOR UPDATE',[Number(departmentId)])).rows[0];if(!current)throw new ApiError(404,'DEPARTMENT_NOT_FOUND','Department not found');if(isActive===false&&current.is_active){const assigned=await client.query(`SELECT COUNT(*)::int count FROM department_heads dh JOIN users u ON u.id=dh.user_id WHERE dh.department_id=$1 AND u.is_active=TRUE`,[current.id]);if(Number(assigned.rows[0].count)>0)throw new ApiError(409,'DEPARTMENT_HAS_ACTIVE_ACCOUNTS','Reassign or deactivate active department accounts first')}
   const next={code:code===undefined?current.department_code:clean(code,50).toUpperCase(),name:name===undefined?current.department_name:clean(name,150),description:description===undefined?current.description:(clean(description,1000)||null),active:isActive===undefined?current.is_active:isActive};if(!next.code||!next.name)throw new ApiError(400,'VALIDATION_ERROR','Department code and official name cannot be blank');const row=(await client.query(`UPDATE departments SET department_code=$2,department_name=$3,description=$4,is_active=$5 WHERE id=$1 RETURNING *`,[current.id,next.code,next.name,next.description,next.active])).rows[0];await client.query(`INSERT INTO audit_logs(user_id,action,table_name,record_id,description)VALUES($1,'DEPARTMENT_UPDATE','departments',$2,$3)`,[Number(actorId),current.id,`Updated department configuration: ${why}`]);await client.query('COMMIT');return publicDepartment(row)}catch(error){try{await client.query('ROLLBACK')}catch(_){}if(error.code==='23505')throw new ApiError(409,'DEPARTMENT_CONFLICT','A department with that code already exists');throw error}finally{client.release()}};
 return{list,create,update};
};
module.exports={createDepartmentAdministrationService,publicDepartment};
