const express=require('express');
const {passwordChange,profile,updateProfile,resendEmail,verifyEmail,requestGoogleEmail,verifyGoogleEmail,googleLink,completeOnboarding}=require('../controllers/accountController');
const router=express.Router();
const avatar=require('../controllers/avatarController');
const {authorizeRoles}=require('../middleware/authMiddleware');
router.get('/avatar',authorizeRoles('DISCIPLINE_ADMIN','DISCIPLINE_OFFICE','DEPARTMENT_HEAD','STUDENT'),avatar.get);
router.patch('/avatar',authorizeRoles('DISCIPLINE_ADMIN','DISCIPLINE_OFFICE','DEPARTMENT_HEAD','STUDENT'),avatar.select);
router.post('/password-change',passwordChange);
router.post('/student-onboarding/google-email/request',requestGoogleEmail);
router.post('/student-onboarding/google-email/verify',verifyGoogleEmail);
router.post('/student-onboarding/google-link',googleLink);
router.post('/student-onboarding/profile',completeOnboarding);
router.get('/admin-profile',profile);
router.patch('/admin-profile',updateProfile);
router.post('/admin-profile/email/resend',resendEmail);
router.post('/admin-profile/email/verify',verifyEmail);
module.exports=router;
