const express = require('express');
const { listConversations, listRecipients, createConversation, getConversation, sendMessage, markConversationRead, updateConversationStatus } = require('../controllers/messageController');
const router = express.Router();
const { authorizePermissions } = require('../middleware/authMiddleware');
const { PERMISSIONS } = require('../security/permissions');
const canMessage = authorizePermissions(PERMISSIONS.PRIVATE_MESSAGES_VIEW);
router.get('/conversations', canMessage, listConversations);
router.get('/recipients', canMessage, listRecipients);
router.post('/conversations', canMessage, createConversation);
router.get('/conversations/:id', canMessage, getConversation);
router.post('/conversations/:id/messages', canMessage, sendMessage);
router.patch('/conversations/:id/read', canMessage, markConversationRead);
router.patch('/conversations/:id/status', canMessage, updateConversationStatus);
module.exports = router;
