import test from 'node:test'
import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import { filterAdminStudents, handbookSanctionGuidance, summarizeStudentCondition } from '../src/lib/adminStudentReview.js'

const students=[{id:1,student_number:'02000123456',first_name:'Juan',last_name:'Dela Cruz',program:'BSIT',section:'A103'},{id:2,student_number:'02000999999',first_name:'Maria',last_name:'Santos',program:'BSTM',section:'B201'}]
test('admin student search matches number, name, program, or section',()=>{assert.deepEqual(filterAdminStudents(students,'dela').map(x=>x.id),[1]);assert.deepEqual(filterAdminStudents(students,'A103').map(x=>x.id),[1]);assert.equal(filterAdminStudents(students,'020009').length,1)})
test('student condition summarizes only that students violation history',()=>{assert.deepEqual(summarizeStudentCondition(1,[{student_id:1,status:'OPEN',required_service_hours:4,completed_service_hours:1},{student_id:1,status:'COMPLETE',required_service_hours:2,completed_service_hours:2},{student_id:2,status:'OPEN',required_service_hours:9}]),{records:[{student_id:1,status:'OPEN',required_service_hours:4,completed_service_hours:1},{student_id:1,status:'COMPLETE',required_service_hours:2,completed_service_hours:2}],total:2,open:1,resolved:1,requiredHours:4,remainingHours:3,condition:'Requires action'})})
test('handbook guidance follows category-specific repeat sequences without inventing service hours',()=>{const guidance=handbookSanctionGuidance([{code:'HANDBOOK_MINOR',name:'Minor',count:2},{code:'HANDBOOK_MAJOR_C',name:'Major C',count:1},{code:'HANDBOOK_MAJOR_D',name:'Major D',count:1}]);assert.equal(guidance[0].guidance,'Written reprimand');assert.match(guidance[1].guidance,/7-10 school days/);assert.match(guidance[2].guidance,/Exclusion or expulsion/);assert.equal(JSON.stringify(guidance).includes('service hours'),false)})
test('student record drawer expands without horizontal overflow and reflows on phones',async()=>{const [app,css]=await Promise.all([readFile(new URL('../src/App.jsx',import.meta.url),'utf8'),readFile(new URL('../src/App.css',import.meta.url),'utf8')]);assert.match(app,/modal-content-card student-record-drawer/);assert.match(css,/\.app-modal--drawer:has\(\.student-record-drawer\) \{ width: min\(780px,100vw\); \}/);assert.match(css,/\.student-record-drawer \.department-stats \{ grid-template-columns: repeat\(4,minmax\(0,1fr\)\); \}/);assert.match(css,/@media \(max-width: 620px\)[\s\S]*?\.student-record-drawer \.department-stats \{ grid-template-columns: repeat\(2,minmax\(0,1fr\)\); \}/)})
