import test from 'node:test'
import assert from 'node:assert/strict'
import { buildDepartmentOfficerPayload, departmentStepValid, filterDepartmentOfficers, officerStepValid } from '../src/lib/departmentOfficerAdmin.js'
import { readFile } from 'node:fs/promises'

test('unified creation payload sends one official department name',()=>{assert.deepEqual(buildDepartmentOfficerPayload({departmentName:'  Student  Affairs ',departmentStatus:'active',username:'  Office.Head ',role:'department_head',firstName:' Ana ',lastName:' Cruz ',email:' ANA@EXAMPLE.COM '}),{department_name:'Student Affairs',description:undefined,department_status:'active',username:'office.head',role:'DEPARTMENT_HEAD',first_name:'Ana',last_name:'Cruz',employee_number:undefined,email:'ana@example.com'})})
test('wizard validates each grouped step',()=>{assert.equal(departmentStepValid({departmentName:'Library'}),true);assert.equal(officerStepValid({firstName:'A',lastName:'B',username:'officer',role:'ADMIN'}),false)})
test('directory filters linked officers by department, role, and status',()=>{const accounts=[{id:1,first_name:'Ana',last_name:'Cruz',username:'ana',role:'DEPARTMENT_HEAD',is_active:true,department_id:4},{id:2,first_name:'Ben',last_name:'Lim',username:'ben',role:'DISCIPLINE_OFFICE',is_active:false}];const departments=[{id:4,department_name:'Library'}];assert.deepEqual(filterDepartmentOfficers(accounts,departments,{search:'library',role:'DEPARTMENT_HEAD',status:'ACTIVE'}).map(x=>x.id),[1])})

test('department tabs use accessible light blue states with a selected indicator',async()=>{const css=await readFile(new URL('../src/styles/portal-system.css',import.meta.url),'utf8');assert.match(css,/\.department-officer-tabs\s*\{[^}]*gap:\s*3px;[^}]*border:\s*1px solid #bed2e6;/s);assert.match(css,/\.department-officer-tabs button:first-child\s*\{[^}]*background:\s*#dceeff !important;[^}]*color:\s*#063b75 !important;/s);assert.match(css,/\.department-officer-tabs button:last-child\s*\{[^}]*background:\s*#dceeff !important;[^}]*color:\s*#063b75 !important;/s);assert.match(css,/button\[aria-selected="true"\]\s*\{[^}]*background:\s*#c7e2fb !important;/s);assert.match(css,/button\[aria-selected="true"\]::after\s*\{[^}]*background:\s*#0b5ea8;/s)})

test('department and officer actions use Title Case',async()=>{const component=await readFile(new URL('../src/components/AdminDepartmentOfficers.jsx',import.meta.url),'utf8');assert.match(component,/>Create Department &amp; Officer</);assert.match(component,/'Create Department & Officer'/);assert.match(component,/>Edit Officer</);assert.match(component,/>Reset Password</)})

test('officer and certificate action groups keep a consistent gap',async()=>{const css=await readFile(new URL('../src/styles/portal-system.css',import.meta.url),'utf8');assert.match(css,/\.main-panel \.inline-actions,\s*\.main-panel \.officer-directory \.registration-review-actions\s*\{[^}]*flex-wrap:\s*wrap;[^}]*gap:\s*10px;/s);assert.match(css,/@media \(max-width: 600px\)[\s\S]*\.main-panel \.inline-actions > button,[\s\S]*min-height:\s*44px;/s)})
