const PERMISSIONS = Object.freeze({
    SYSTEM_HEALTH_VIEW: 'SYSTEM_HEALTH_VIEW',
    SYSTEM_VERSION_VIEW: 'SYSTEM_VERSION_VIEW',
    INTEGRATION_STATUS_VIEW: 'INTEGRATION_STATUS_VIEW',
    FAILED_JOBS_VIEW: 'FAILED_JOBS_VIEW',
    SECURITY_EVENTS_VIEW: 'SECURITY_EVENTS_VIEW',
    AUTH_ACTIVITY_VIEW: 'AUTH_ACTIVITY_VIEW',
    TECHNICAL_AUDIT_VIEW: 'TECHNICAL_AUDIT_VIEW',
    SYSTEM_CONFIG_SAFE_MANAGE: 'SYSTEM_CONFIG_SAFE_MANAGE',
    ACCOUNT_LOCK: 'ACCOUNT_LOCK',
    ACCOUNT_RECOVERY_INITIATE: 'ACCOUNT_RECOVERY_INITIATE',
    MAINTENANCE_TOOLS_USE: 'MAINTENANCE_TOOLS_USE',
    SUPPORT_ACCESS_REQUEST: 'SUPPORT_ACCESS_REQUEST',
    SUPPORT_ACCESS_HISTORY_VIEW: 'SUPPORT_ACCESS_HISTORY_VIEW',
    STAFF_ACCOUNT_MANAGE: 'STAFF_ACCOUNT_MANAGE',
    STUDENT_REGISTRATION_REVIEW: 'STUDENT_REGISTRATION_REVIEW',
    STUDENT_BASIC_VIEW: 'STUDENT_BASIC_VIEW',
    STUDENT_RESTRICTED_VIEW: 'STUDENT_RESTRICTED_VIEW',
    STUDENT_MANAGE: 'STUDENT_MANAGE',
    DEPARTMENT_MANAGE: 'DEPARTMENT_MANAGE',
    OFFICER_ASSIGNMENT_MANAGE: 'OFFICER_ASSIGNMENT_MANAGE',
    VIOLATION_CREATE: 'VIOLATION_CREATE',
    VIOLATION_UPDATE: 'VIOLATION_UPDATE',
    VIOLATION_COMPLETE: 'VIOLATION_COMPLETE',
    VIOLATION_CLEAR: 'VIOLATION_CLEAR',
    VIOLATION_INVALIDATE: 'VIOLATION_INVALIDATE',
    VIOLATION_REOPEN: 'VIOLATION_REOPEN',
    SERVICE_ASSIGNMENT_MANAGE: 'SERVICE_ASSIGNMENT_MANAGE',
    ATTENDANCE_SCAN: 'ATTENDANCE_SCAN',
    DTR_CORRECT: 'DTR_CORRECT',
    CLEARANCE_REVIEW: 'CLEARANCE_REVIEW',
    CLEARANCE_APPROVE: 'CLEARANCE_APPROVE',
    CLEARANCE_CERTIFICATE_ISSUE: 'CLEARANCE_CERTIFICATE_ISSUE',
    ESIGNATURE_MANAGE: 'ESIGNATURE_MANAGE',
    REPORT_VIEW: 'REPORT_VIEW',
    DEPARTMENT_REPORT_VIEW: 'DEPARTMENT_REPORT_VIEW',
    DATA_EXPORT: 'DATA_EXPORT',
    PRIVATE_MESSAGES_VIEW: 'PRIVATE_MESSAGES_VIEW',
    GUARDIAN_CONTACT_VIEW: 'GUARDIAN_CONTACT_VIEW',
    OPERATIONAL_SETTINGS_MANAGE: 'OPERATIONAL_SETTINGS_MANAGE',
    OPERATIONAL_AUDIT_VIEW: 'OPERATIONAL_AUDIT_VIEW',
    SUPPORT_ACCESS_APPROVE: 'SUPPORT_ACCESS_APPROVE'
});

const operationalAdmin = [
    'STAFF_ACCOUNT_MANAGE', 'STUDENT_REGISTRATION_REVIEW', 'STUDENT_BASIC_VIEW',
    'STUDENT_RESTRICTED_VIEW', 'STUDENT_MANAGE', 'DEPARTMENT_MANAGE',
    'OFFICER_ASSIGNMENT_MANAGE', 'VIOLATION_CREATE', 'VIOLATION_UPDATE',
    'VIOLATION_COMPLETE', 'VIOLATION_CLEAR', 'VIOLATION_INVALIDATE',
    'VIOLATION_REOPEN', 'SERVICE_ASSIGNMENT_MANAGE', 'ATTENDANCE_SCAN',
    'DTR_CORRECT', 'CLEARANCE_REVIEW', 'CLEARANCE_APPROVE',
    'CLEARANCE_CERTIFICATE_ISSUE', 'ESIGNATURE_MANAGE', 'REPORT_VIEW',
    'DATA_EXPORT', 'PRIVATE_MESSAGES_VIEW', 'GUARDIAN_CONTACT_VIEW',
    'OPERATIONAL_SETTINGS_MANAGE', 'OPERATIONAL_AUDIT_VIEW',
    'SUPPORT_ACCESS_APPROVE'
];

const ROLE_PERMISSIONS = Object.freeze({
    SYSTEM_ADMIN: new Set([
        'SYSTEM_HEALTH_VIEW', 'SYSTEM_VERSION_VIEW', 'INTEGRATION_STATUS_VIEW',
        'FAILED_JOBS_VIEW', 'SECURITY_EVENTS_VIEW', 'AUTH_ACTIVITY_VIEW',
        'TECHNICAL_AUDIT_VIEW', 'SYSTEM_CONFIG_SAFE_MANAGE', 'ACCOUNT_LOCK',
        'ACCOUNT_RECOVERY_INITIATE', 'MAINTENANCE_TOOLS_USE',
        'SUPPORT_ACCESS_REQUEST', 'SUPPORT_ACCESS_HISTORY_VIEW'
    ]),
    DISCIPLINE_ADMIN: new Set(operationalAdmin),
    DISCIPLINE_OFFICE: new Set([
        'STUDENT_REGISTRATION_REVIEW', 'STUDENT_BASIC_VIEW', 'STUDENT_RESTRICTED_VIEW',
        'STUDENT_MANAGE', 'VIOLATION_CREATE', 'VIOLATION_UPDATE',
        'VIOLATION_COMPLETE', 'SERVICE_ASSIGNMENT_MANAGE', 'ATTENDANCE_SCAN',
        'CLEARANCE_REVIEW', 'CLEARANCE_APPROVE', 'CLEARANCE_CERTIFICATE_ISSUE',
        'ESIGNATURE_MANAGE', 'REPORT_VIEW', 'DATA_EXPORT', 'DTR_CORRECT',
        'PRIVATE_MESSAGES_VIEW', 'GUARDIAN_CONTACT_VIEW'
    ]),
    DEPARTMENT_HEAD: new Set(['STUDENT_BASIC_VIEW', 'ATTENDANCE_SCAN', 'DEPARTMENT_REPORT_VIEW', 'PRIVATE_MESSAGES_VIEW']),
    STUDENT: new Set(['PRIVATE_MESSAGES_VIEW'])
});

const permissionsForRole = (role) => new Set(ROLE_PERMISSIONS[role] || []);
const roleHasPermission = (role, permission) => permissionsForRole(role).has(permission);

module.exports = { PERMISSIONS, ROLE_PERMISSIONS, permissionsForRole, roleHasPermission };
